#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
CLI entry point and orchestration for data masking.

Extracted from data_masking.py during the package refactoring (v2.5.0).
"""

import json
import os
import sys
import random
import argparse
from pathlib import Path
from datetime import datetime
from typing import Any, Dict, Optional, Tuple

from datamasking._fsutil import atomic_write_private
from datamasking.masking import constants as _cfg
from datamasking.masking.helpers import validate_file_size

# Коди виходу: 0 — успіх, 1 — помилка виконання, 2 — помилка використання CLI
EXIT_OK = 0
EXIT_ERROR = 1
EXIT_USAGE = 2

# Єдина env-змінна для пароля (та сама на боці unmask)
PASSWORD_ENV_DEFAULT = "DATA_MASKING_PASSWORD"
from datamasking.masking.engine import (
    mask_text_context_aware, mask_json_recursive,
)

# ============================================================================
# OPTIONAL MODULES
# ============================================================================
import logging as _logging
_opt_logger = _logging.getLogger(__name__)

try:
    from datamasking.extras.selective import (
        get_available_types, get_types_help, create_filter, apply_filter_to_globals,
    )
    SELECTIVE_AVAILABLE = True
except ImportError:
    SELECTIVE_AVAILABLE = False
    _opt_logger.debug("datamasking.extras.selective not available — --only/--exclude disabled")

try:
    from datamasking.extras.re_mask import MappingChain, make_empty_masking_dict
    REMASK_AVAILABLE = True
except ImportError:
    REMASK_AVAILABLE = False
    _opt_logger.debug("datamasking.extras.re_mask not available — re-masking disabled")

try:
    from datamasking.extras.security import MappingSecurityManager, is_encryption_available
    SECURITY_AVAILABLE = True
except ImportError:
    SECURITY_AVAILABLE = False

    def is_encryption_available() -> bool:  # type: ignore[misc]
        return False
    _opt_logger.debug("datamasking.extras.security not available — encryption disabled")

try:
    from datamasking.extras.config import ConfigLoader
    CONFIG_AVAILABLE = True
except ImportError:
    CONFIG_AVAILABLE = False
    _opt_logger.debug("datamasking.extras.config not available — YAML config disabled")

try:
    from datamasking.extras.masking_logger import setup_logging
    LOGGING_AVAILABLE = True
except ImportError:
    LOGGING_AVAILABLE = False
    _opt_logger.debug("datamasking.extras.masking_logger not available — structured logging disabled")

try:
    from datamasking.extras.password_generator import generate_password
    PASSWORD_GENERATOR_AVAILABLE = True
except ImportError:
    PASSWORD_GENERATOR_AVAILABLE = False
    _opt_logger.debug("datamasking.extras.password_generator not available — password generation disabled")


# ============================================================================
# UTILITY FUNCTIONS
# ============================================================================

def generate_default_config(output_path: str) -> None:
    """Generate a default config.yaml file.

    Єдине джерело шаблону — ConfigLoader (extras/config.py): раніше CLI мав
    власну копію, яка розходилась зі схемою loader-а
    (`security.password_generation: true` замість секції).
    """
    if CONFIG_AVAILABLE:
        ConfigLoader.generate_default_config(output_path)
        return
    config_content = f"""\
# Data Masking Configuration v{_cfg.__version__}
# Generated by data_masking.py

system:
  version: "v{_cfg.__version__}"
  hash_algorithm: "blake2b"
  preserve_case: true
  debug_mode: false

security:
  encrypt_output: false
  password_generation: true
  password_env_var: "DATA_MASKING_PASSWORD"
  password_length: 24

masking_rules:
  enable_ranks: true
  enable_names: true
  enable_ipn: true
  enable_passport: true
  enable_military_id: true
  enable_dates: true
  enable_brigades: true
  enable_units: true
  enable_orders: true
  enable_br_numbers: true

logging:
  level: "INFO"
  file: null
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

router_rules:
  default_action: "mask"
"""
    Path(output_path).write_text(config_content, encoding='utf-8')


def generate_password_from_config(config) -> str:
    """Generate a secure password, optionally using config settings."""
    import secrets
    import string
    length = 24
    if config is not None:
        length = getattr(getattr(config, 'security', None),
                         'password_length', 24)
    alphabet = string.ascii_letters + string.digits + "!@#$%^&*"
    return ''.join(secrets.choice(alphabet) for _ in range(length))


def _build_parser() -> argparse.ArgumentParser:
    """Build and return the CLI argument parser."""
    parser = argparse.ArgumentParser(
        description=f"Data Masking Script v{_cfg.__version__}",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("-V", "--version", action="version",
                        version=f"%(prog)s {_cfg.__version__}")
    parser.add_argument("-i", "--input", default="input.txt", help="Input file")
    parser.add_argument("-o", "--output", help="Output file (mapping and report are written next to it)")
    parser.add_argument("--force", action="store_true",
                        help="Overwrite an existing output file")
    parser.add_argument("--no-report", action="store_true", help="No report")
    parser.add_argument("--debug", action="store_true", help="Debug mode")
    parser.add_argument("--init-config", action="store_true",
                        help="Generate default config.yaml and exit")
    parser.add_argument("--config", type=str, default=None,
                        help="Path to YAML configuration file")
    parser.add_argument("--log-level", type=str, default=None,
                        choices=["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"],
                        help="Logging level")
    parser.add_argument("--log-file", type=str, default=None,
                        help="Path to log file")

    if SELECTIVE_AVAILABLE:
        parser.add_argument("--only", nargs="+", metavar="TYPE",
                            help="Mask only these types (space- or comma-separated; "
                                 "groups and aliases accepted, see --list-types)")
        parser.add_argument("--exclude", nargs="+", metavar="TYPE",
                            help="Mask everything except these types")
        parser.add_argument("--list-types", action="store_true",
                            help="List available masking types, groups and aliases, then exit")

    if SECURITY_AVAILABLE:
        parser.add_argument("--encrypt", action="store_true",
                            help="Encrypt the mapping file")
        parser.add_argument("--password", type=str, default=None,
                            help="Password for encryption (visible in process list; "
                                 "prefer --password-env)")
        parser.add_argument("--password-env", type=str, default=None, metavar="VAR",
                            help=f"Environment variable holding the password "
                                 f"(default lookup: {PASSWORD_ENV_DEFAULT})")

    if REMASK_AVAILABLE:
        parser.add_argument("--re-mask", type=int, default=None, metavar="N",
                            help="Number of re-masking passes (2-10)")

    return parser


def _load_config(args) -> Tuple[Optional[Any], Optional[str]]:
    """Load configuration: YAML (якщо є) + ENV-перекриття.

    Раніше без config.yaml loader узагалі не запускався, і всі
    DATA_MASKING_* змінні мовчки ігнорувались; битий YAML давав дефолти
    з написом «Loaded config». Тепер: loader працює завжди (ENV діє без
    файлу), помилка читання/розбору явно вказаного або наявного файлу —
    фатальна для CLI.

    Returns:
        (config, None) або (None, error_message)
    """
    if not CONFIG_AVAILABLE:
        return None, None

    config_path = args.config
    if config_path is not None and not Path(config_path).exists():
        return None, f"Config file not found: {config_path}"

    try:
        loader = ConfigLoader(config_path)
        config = loader.load()
    except (FileNotFoundError, PermissionError, ValueError, OSError) as e:
        return None, f"Could not load config: {e}"

    source = loader.loaded_from
    if source:
        print(f"Loaded config from {source}")
    try:
        config._source = source  # для звіту; dataclass дозволяє атрибут
    except AttributeError:
        pass
    return config, None


def _setup_logger(args, config) -> Optional[Any]:
    """Set up structured logging."""
    if not LOGGING_AVAILABLE:
        return None

    log_level = args.log_level
    log_file = args.log_file

    if config is not None:
        if log_level is None:
            log_level = getattr(getattr(config, 'logging', None), 'level', None)
        if log_file is None:
            log_file = getattr(getattr(config, 'logging', None), 'file', None)

    if log_level is None:
        log_level = "INFO"

    try:
        logger = setup_logging(level=log_level, log_file=log_file)
        logger.info(f"Data Masking Script v{_cfg.__version__} started")
        return logger
    except (ValueError, OSError, TypeError) as e:
        print(f"Warning: could not setup logging: {e}")
        return None


def _apply_selective_filters(args, logger) -> Optional[str]:
    """Apply --only / --exclude selective masking filters.

    Розбір імен типів делеговано extras.selective (канонічні імена,
    множина, українські форми, групи, кома/пробіл як роздільник) — раніше
    CLI мав власну несумісну таблицю, і невідомий тип тихо давав
    «замасковано нічого» з exit 0.

    Returns:
        None — ок; рядок з помилкою — невідомий тип (виклик має завершити
        роботу з EXIT_USAGE, НЕ записавши жодного файлу).
    """
    if not SELECTIVE_AVAILABLE:
        return None

    only_types = getattr(args, 'only', None)
    exclude_types = getattr(args, 'exclude', None)

    if not only_types and not exclude_types:
        return None

    if only_types and exclude_types:
        return "--only and --exclude cannot be combined"

    only_str = " ".join(only_types) if only_types else None
    exclude_str = " ".join(exclude_types) if exclude_types else None
    try:
        selective_filter = create_filter(only=only_str, exclude=exclude_str)
    except ValueError as e:
        if logger:
            logger.error(f"Selective masking: {e}")
        return str(e)

    if not selective_filter.enabled_types:
        return "Selective masking would disable every type — nothing to do"

    apply_filter_to_globals(selective_filter, vars(_cfg))

    mode = "--only" if only_types else "--exclude"
    enabled = ", ".join(selective_filter.get_enabled_list())
    print(f"Selective masking: {mode} {only_str or exclude_str} → enabled: {enabled}")
    if logger:
        logger.info(f"Selective masking: {mode} {only_str or exclude_str} → enabled: {enabled}")
    return None


def _apply_config_settings(args, config, logger) -> None:
    """Apply config-based masking rules and system settings."""
    if config is None:
        return

    # Masking rules from config (only if --only/--exclude not specified)
    masking_rules = getattr(config, 'masking_rules', None)
    if masking_rules is not None:
        only_types = getattr(args, 'only', None) if SELECTIVE_AVAILABLE else None
        exclude_types = getattr(args, 'exclude', None) if SELECTIVE_AVAILABLE else None

        if not only_types and not exclude_types:
            config_rules_map = {
                'enable_ranks': 'MASK_RANKS',
                'enable_names': 'MASK_NAMES',
                'enable_ipn': 'MASK_IPN',
                'enable_passport': 'MASK_PASSPORT',
                'enable_military_id': 'MASK_MILITARY_ID',
                'enable_dates': 'MASK_DATES',
                'enable_brigades': 'MASK_BRIGADES',
                'enable_units': 'MASK_UNITS',
                'enable_orders': 'MASK_ORDERS',
                'enable_br_numbers': 'MASK_BR_NUMBERS',
            }
            for config_key, global_var in config_rules_map.items():
                value = getattr(masking_rules, config_key, None)
                if value is not None:
                    setattr(_cfg, global_var, bool(value))
                    if logger:
                        logger.debug(f"Config: {config_key} = {value}")

    # System settings from config
    system_cfg = getattr(config, 'system', None)
    if system_cfg is not None:
        cfg_debug = getattr(system_cfg, 'debug_mode', None)
        if cfg_debug is not None and not args.debug:
            _cfg.DEBUG_MODE = bool(cfg_debug)

        cfg_preserve_case = getattr(system_cfg, 'preserve_case', None)
        if cfg_preserve_case is not None:
            _cfg.PRESERVE_CASE = bool(cfg_preserve_case)

        cfg_hash = getattr(system_cfg, 'hash_algorithm', None)
        if cfg_hash is not None:
            _cfg.HASH_ALGORITHM = str(cfg_hash)

    # validation.max_input_size_mb — раніше документований, але мертвий ключ
    validation_cfg = getattr(config, 'validation', None)
    max_mb = getattr(validation_cfg, 'max_input_size_mb', None)
    if isinstance(max_mb, int) and max_mb > 0:
        _cfg.MAX_INPUT_FILE_SIZE = max_mb * 1024 * 1024

    # security.encrypt_output — те саме, що --encrypt (раніше ігнорувався)
    security_cfg = getattr(config, 'security', None)
    if getattr(security_cfg, 'encrypt_output', False) and hasattr(args, 'encrypt') and not args.encrypt:
        args.encrypt = True
        if logger:
            logger.info("Encryption enabled by config (security.encrypt_output)")


def _prepare_output_paths(args, input_path: Path) -> Tuple[Path, Path, Path, str, int]:
    """Determine output, mapping, and report file paths.

    Mapping і звіт лягають ПОРУЧ із вихідним файлом (раніше — завжди у cwd,
    тож при `-o dir/x.txt` unmask не знаходив пару).
    """
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    is_json = input_path.suffix.lower() == '.json'
    ext = '.json' if is_json else '.txt'

    # Суфікс перекидаємо, поки набір імен не унікальний: два запуски в одну
    # секунду раніше могли мовчки перезаписати файли одне одного (p≈1/900)
    for _ in range(50):
        random_suffix = random.randint(100, 999)
        output_path = Path(args.output) if args.output else Path(f"output_{timestamp}_{random_suffix}{ext}")
        out_dir = output_path.parent
        map_path = out_dir / f"masking_map_{timestamp}_{random_suffix}.json"
        report_path = out_dir / f"masking_report_{timestamp}_{random_suffix}.txt"
        clashes = [map_path, map_path.with_suffix('.enc'), report_path]
        if not args.output:
            clashes.append(output_path)
        if not any(p.exists() for p in clashes):
            break

    return output_path, map_path, report_path, timestamp, random_suffix


def _validate_output_paths(args, input_path: Path, output_path: Path) -> Optional[str]:
    """Захист від втрати даних: -o не може вказувати на вхід і не
    перезаписує існуючий файл без --force. Повертає текст помилки або None."""
    try:
        same = output_path.resolve() == input_path.resolve()
    except OSError:
        same = False
    if same:
        return f"Output file must differ from input file: {output_path}"
    if output_path.exists() and not getattr(args, 'force', False):
        return f"Output file already exists: {output_path} (use --force to overwrite)"
    return None


def _resolve_password(args, config, logger) -> Tuple[Optional[str], Optional[str]]:
    """Визначає пароль для --encrypt ДО запису будь-яких файлів.

    Пріоритет: --password → --password-env VAR → $DATA_MASKING_PASSWORD →
    згенерований (показується один раз у stderr).
    Явно вказана, але порожня/відсутня змінна — помилка, а не мовчазна
    підміна випадковим паролем.

    Returns:
        (password, None) або (None, error_message)
    """
    password = getattr(args, 'password', None)
    if password is not None:
        if not password:
            return None, "--password must not be empty"
        return password, None

    password_env = getattr(args, 'password_env', None)
    if password_env:
        password = os.environ.get(password_env)
        if not password:
            return None, f"Environment variable '{password_env}' is not set or empty"
        return password, None

    password = os.environ.get(PASSWORD_ENV_DEFAULT)
    if password:
        if logger:
            logger.info(f"Password taken from ${PASSWORD_ENV_DEFAULT}")
        return password, None

    password = generate_password_from_config(config)
    _print_generated_password(password)
    return password, None


def _read_input(input_path: Path, is_json: bool, logger):
    """Read input file (JSON or text)."""
    try:
        validate_file_size(input_path, _cfg.MAX_INPUT_FILE_SIZE)
        with open(input_path, 'r', encoding='utf-8', newline='') as f:
            if is_json:
                return json.load(f)
            else:
                return f.read()
    except (FileNotFoundError, PermissionError, OSError, json.JSONDecodeError,
            UnicodeDecodeError, ValueError) as e:
        print(f"Error reading file: {e}")
        if logger:
            logger.error(f"Error reading file: {e}")
        return None


def _run_masking(input_data, is_json: bool, masking_dict: Dict,
                 instance_counters: Dict, args, logger,
                 timestamp: str, random_suffix: int) -> Tuple[Any, int, Optional[Any]]:
    """Execute single-pass or multi-pass masking.

    Returns:
        (masked_data, total_unique, chain) — chain є лише у multi-pass
        режимі; його збереження (і шифрування) робить _save_results.
    """
    re_mask_passes = getattr(args, 're_mask', None)

    if re_mask_passes is not None:
        if re_mask_passes < 2:
            print("Warning: --re-mask requires at least 2 passes, using single-pass mode")
            if logger:
                logger.warning("--re-mask value < 2, falling back to single-pass")
            re_mask_passes = None
        elif re_mask_passes > 10:
            print(f"Warning: --re-mask capped at 10 passes (was {re_mask_passes})")
            if logger:
                logger.warning(f"--re-mask capped at 10 (requested {re_mask_passes})")
            re_mask_passes = 10

    if REMASK_AVAILABLE and re_mask_passes and re_mask_passes > 1:
        return _run_multi_pass_masking(
            input_data, is_json, masking_dict, args, logger,
            re_mask_passes, timestamp, random_suffix
        )
    else:
        masked_data, total_unique = _run_single_pass_masking(
            input_data, is_json, masking_dict, instance_counters, logger
        )
        return masked_data, total_unique, None


def _run_multi_pass_masking(input_data, is_json: bool, masking_dict: Dict,
                            args, logger, re_mask_passes: int,
                            timestamp: str, random_suffix: int) -> Tuple[Any, int, Any]:
    """Execute multi-pass re-masking with chain tracking.

    Chain НЕ зберігається тут — _save_results запише його (plaintext або
    .enc при --encrypt) поруч із вихідним файлом.
    """
    if logger:
        logger.info(f"Starting multi-pass re-masking ({re_mask_passes} passes)")

    chain = MappingChain()
    masked_data = input_data

    for pass_num in range(1, re_mask_passes + 1):
        print(f"  Прохід {pass_num}/{re_mask_passes}...")
        if logger:
            logger.info(f"Re-masking pass {pass_num}/{re_mask_passes}")

        pass_dict = make_empty_masking_dict(_cfg.__version__)
        pass_counters = {}

        if is_json:
            masked_data = mask_json_recursive(masked_data, pass_dict, pass_counters)
        else:
            masked_data = mask_text_context_aware(masked_data, pass_dict, pass_counters)

        pass_dict["instance_tracking"] = pass_counters
        for category, mappings in pass_dict["mappings"].items():
            pass_dict["statistics"][category] = len(mappings)
        chain.add_pass(pass_dict)

    masking_dict["instance_tracking"] = {}
    total_unique = 0
    for p in chain.passes:
        for cat, count in p.get("statistics", {}).items():
            masking_dict["statistics"][cat] = masking_dict["statistics"].get(cat, 0) + count
            if cat != "total_masked":
                total_unique += count
    masking_dict["statistics"]["total_masked"] = total_unique

    return masked_data, total_unique, chain


def _run_single_pass_masking(input_data, is_json: bool, masking_dict: Dict,
                             instance_counters: Dict, logger) -> Tuple[Any, int]:
    """Execute single-pass masking."""
    if logger:
        logger.info("Starting single-pass masking")

    if is_json:
        masked_data = mask_json_recursive(input_data, masking_dict, instance_counters)
    else:
        masked_data = mask_text_context_aware(input_data, masking_dict, instance_counters)

    masking_dict["instance_tracking"] = instance_counters

    total_unique = 0
    for category, mappings in masking_dict["mappings"].items():
        count = len(mappings)
        masking_dict["statistics"][category] = count
        total_unique += count
    masking_dict["statistics"]["total_masked"] = total_unique

    return masked_data, total_unique


def _print_generated_password(password: str) -> None:
    """Показує згенерований пароль у stderr (не stdout), щоб він не
    потрапляв у перенаправлений вивід, пайпи та логи CI."""
    import sys
    print("  Generated password (shown once, NOT saved anywhere):",
          file=sys.stderr)
    print(f"  {password}", file=sys.stderr)


def _write_mapping(mapping: Dict, json_path: Path, password: Optional[str],
                   logger) -> Path:
    """Записує mapping (звичайний або chain) — ОДИН файл.

    Без пароля: plaintext JSON (атомарно, 0600).
    З паролем: лише .enc — plaintext на диск не потрапляє взагалі
    (раніше --encrypt писав .json І .enc поруч).
    """
    if password:
        enc_path = json_path.with_suffix('.enc')
        MappingSecurityManager().encrypt_mapping(mapping, password, enc_path)
        if logger:
            logger.info(f"Mapping encrypted to {enc_path}")
        return enc_path

    payload = json.dumps(mapping, ensure_ascii=False, indent=2).encode("utf-8")
    atomic_write_private(json_path, payload)
    return json_path


def _write_report(report_path: Path, masking_dict: Dict, input_path: Path,
                  output_path: Path, is_json: bool, total_unique: int,
                  re_mask_passes, args, config) -> None:
    """Generate the detailed masking report file."""
    with open(report_path, 'w', encoding='utf-8') as f:
        f.write("=" * 60 + "\n")
        f.write("ЗВІТ МАСКУВАННЯ ДАНИХ\n")
        f.write("=" * 60 + "\n\n")
        f.write(f"Версія: {_cfg.__version__}\n")
        f.write(f"Дата та час: {masking_dict['timestamp']}\n")
        f.write(f"Вхідний файл: {input_path}\n")
        f.write(f"Вихідний файл: {output_path}\n")
        f.write(f"Формат: {'JSON' if is_json else 'TXT'}\n")

        f.write("\n" + "-" * 60 + "\n")
        f.write("КОНФІГУРАЦІЯ МАСКУВАННЯ\n")
        f.write("-" * 60 + "\n\n")
        f.write(f"  Імена (MASK_NAMES): {_cfg.MASK_NAMES}\n")
        f.write(f"  ІПН (MASK_IPN): {_cfg.MASK_IPN}\n")
        f.write(f"  Паспорти (MASK_PASSPORT): {_cfg.MASK_PASSPORT}\n")
        f.write(f"  Військові ID (MASK_MILITARY_ID): {_cfg.MASK_MILITARY_ID}\n")
        f.write(f"  Звання (MASK_RANKS): {_cfg.MASK_RANKS}\n")
        f.write(f"  Бригади (MASK_BRIGADES): {_cfg.MASK_BRIGADES}\n")
        f.write(f"  Частини (MASK_UNITS): {_cfg.MASK_UNITS}\n")
        f.write(f"  Накази (MASK_ORDERS): {_cfg.MASK_ORDERS}\n")
        f.write(f"  БР номери (MASK_BR_NUMBERS): {_cfg.MASK_BR_NUMBERS}\n")
        f.write(f"  Дати (MASK_DATES): {_cfg.MASK_DATES}\n")
        f.write(f"  Збереження регістру (PRESERVE_CASE): {_cfg.PRESERVE_CASE}\n")
        f.write(f"  Алгоритм хешування: {_cfg.HASH_ALGORITHM}\n")

        if re_mask_passes and re_mask_passes > 1:
            f.write(f"\n  Режим: повторне маскування ({re_mask_passes} проходів)\n")
        else:
            f.write(f"\n  Режим: одинарне маскування\n")

        config_source = getattr(config, '_source', None)
        if config_source:
            f.write(f"  Конфігурація: {config_source}\n")

        f.write("\n" + "-" * 60 + "\n")
        f.write("СТАТИСТИКА МАСКУВАННЯ\n")
        f.write("-" * 60 + "\n\n")
        f.write(f"Загальна кількість УНІКАЛЬНИХ замаскованих елементів: {total_unique}\n\n")

        for key, value in sorted(masking_dict["statistics"].items()):
            if key != "total_masked" and value > 0:
                f.write(f"  • {key}: {value} (унікальних оригіналів)\n")

        f.write("\n" + "=" * 60 + "\n")
        f.write("СТАТИСТИКА ВХОДЖЕНЬ (Instance Tracking)\n")
        f.write("-" * 60 + "\n\n")

        sorted_report_instances = sorted(
            masking_dict["instance_tracking"].items(),
            key=lambda x: x[1],
            reverse=True
        )
        for masked_val, count in sorted_report_instances:
            f.write(f"  • '{masked_val}': {count} входжень\n")

        f.write("\n" + "=" * 60 + "\n")
        f.write(f"Кінець звіту. Всього записів у instance tracking: "
                f"{len(masking_dict['instance_tracking'])}\n")
        f.write("=" * 60 + "\n")


def _print_summary(masking_dict: Dict, total_unique: int,
                   output_path: Path, map_path: Path,
                   report_path: Optional[Path], logger) -> None:
    """Print masking summary to console."""
    print()
    print("✅ Маскування завершено успішно!")
    print()
    print(f"📊 Статистика:")
    print(f"   Загальна кількість УНІКАЛЬНИХ замаскованих елементів: {total_unique}")
    for key, value in sorted(masking_dict["statistics"].items()):
        if key != "total_masked" and value > 0:
            print(f"   • {key}: {value} (унікальних оригіналів)")
    print()
    print(f"   Статистика входжень (Instance Tracking):")
    sorted_instances = sorted(masking_dict["instance_tracking"].items(), key=lambda x: x[1], reverse=True)
    for masked_val, count in sorted_instances[:10]:
        print(f"   • '{masked_val}': {count} входжень")
    if len(sorted_instances) > 10:
        print(f"   ... та ще {len(sorted_instances) - 10} записів")

    print()
    print(f"📁 Файли збережено:")
    print(f"   • Замасковані дані: {output_path.absolute()}")
    print(f"   • Словник замін: {map_path.absolute()}")
    if report_path:
        print(f"   • Звіт: {report_path.absolute()}")

    if logger:
        logger.info(f"Masking completed: {total_unique} unique items masked")
        logger.info(f"Output: {output_path.absolute()}")
        logger.info(f"Mapping: {map_path.absolute()}")


def _save_results(masked_data, is_json: bool, masking_dict: Dict,
                  output_path: Path, map_path: Path, report_path: Path,
                  total_unique: int, args, config, logger,
                  chain=None, password: Optional[str] = None) -> int:
    """Save masked output, mapping (or chain), and report. Returns exit code."""
    re_mask_passes = getattr(args, 're_mask', None)

    try:
        with open(output_path, 'w', encoding='utf-8', newline='') as f:
            if is_json:
                json.dump(masked_data, f, ensure_ascii=False, indent=2)
            else:
                f.write(masked_data)

        if chain is not None:
            chain_json = map_path.with_name(map_path.name.replace("masking_map_", "masking_chain_", 1))
            written_map = _write_mapping(chain.to_dict(), chain_json, password, logger)
            print(f"  Chain mapping ({len(chain.passes)} passes): {written_map}")
        else:
            written_map = _write_mapping(masking_dict, map_path, password, logger)
        if password:
            print(f"  Encrypted mapping: {written_map}")

        # Generate report
        if not args.no_report:
            _write_report(report_path, masking_dict, Path(args.input),
                          output_path, is_json, total_unique,
                          re_mask_passes, args, config)

        _print_summary(
            masking_dict, total_unique, output_path, written_map,
            report_path if not args.no_report else None, logger
        )
        return EXIT_OK

    except (OSError, PermissionError, json.JSONDecodeError, UnicodeEncodeError, RuntimeError) as e:
        print(f"❌ Помилка збереження файлів: {e}")
        if logger:
            logger.error(f"Error saving files: {e}")
        return EXIT_ERROR


def main(argv=None) -> int:
    """CLI entry point. Повертає код виходу (0/1/2); обгортки роблять
    sys.exit(main()), тому помилки більше не завершуються exit 0."""
    # Fix Unicode output on Windows (cp1252 console): інакше «✅» у підсумку
    # падав UnicodeEncodeError уже ПІСЛЯ запису файлів (unmask мав цей фікс, mask — ні)
    if sys.platform == 'win32' and getattr(sys.stdout, 'encoding', 'utf-8').lower().replace('-', '') != 'utf8':
        import io
        sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
        sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8', errors='replace')

    parser = _build_parser()
    args = parser.parse_args(argv)

    # ================================================================
    # Handle --init-config (early exit)
    # ================================================================
    if args.init_config:
        if Path("config.yaml").exists() and not args.force:
            print("Error: config.yaml already exists (use --force to overwrite)")
            return EXIT_ERROR
        generate_default_config("config.yaml")
        print("Generated config.yaml")
        return EXIT_OK

    # ================================================================
    # Handle --list-types (early exit)
    # ================================================================
    if SELECTIVE_AVAILABLE and getattr(args, 'list_types', False):
        print(get_types_help())
        return EXIT_OK

    # ================================================================
    # Setup: config, logging, filters, system settings
    # ================================================================
    config, config_error = _load_config(args)
    if config_error:
        print(f"Error: {config_error}")
        return EXIT_ERROR
    logger = _setup_logger(args, config)

    if args.debug:
        _cfg.DEBUG_MODE = True

    filter_error = _apply_selective_filters(args, logger)
    if filter_error:
        print(f"Error: {filter_error}")
        return EXIT_USAGE
    _apply_config_settings(args, config, logger)

    if logger:
        logger.info(f"Masking flags: NAMES={_cfg.MASK_NAMES}, IPN={_cfg.MASK_IPN}, "
                     f"PASSPORT={_cfg.MASK_PASSPORT}, MILITARY_ID={_cfg.MASK_MILITARY_ID}, "
                     f"RANKS={_cfg.MASK_RANKS}, BRIGADES={_cfg.MASK_BRIGADES}, "
                     f"UNITS={_cfg.MASK_UNITS}, ORDERS={_cfg.MASK_ORDERS}, "
                     f"BR_NUMBERS={_cfg.MASK_BR_NUMBERS}, DATES={_cfg.MASK_DATES}")

    # ================================================================
    # Input file validation and path setup
    # ================================================================
    input_path = Path(args.input)
    if not input_path.exists():
        print(f"Error: {args.input} not found")
        if logger:
            logger.error(f"Input file not found: {args.input}")
        return EXIT_ERROR

    output_path, map_path, report_path, timestamp, random_suffix = \
        _prepare_output_paths(args, input_path)

    path_error = _validate_output_paths(args, input_path, output_path)
    if path_error:
        print(f"Error: {path_error}")
        if logger:
            logger.error(path_error)
        return EXIT_USAGE

    # Пароль визначаємо ДО будь-якого запису: помилка тут не лишає
    # напівготових файлів на диску
    password = None
    if getattr(args, 'encrypt', False) and not is_encryption_available():
        # Ядро без extras: чиста помилка ДО запису файлів, а не traceback
        print("Error: --encrypt requires the 'cryptography' package "
              "(pip install 'data-masking[security]')")
        return EXIT_ERROR
    if SECURITY_AVAILABLE and getattr(args, 'encrypt', False):
        password, pw_error = _resolve_password(args, config, logger)
        if pw_error:
            print(f"Error: {pw_error}")
            if logger:
                logger.error(pw_error)
            return EXIT_USAGE
    elif getattr(args, 'encrypt', False):
        print("Error: --encrypt requires the 'cryptography' package (pip install 'data-masking[security]')")
        return EXIT_ERROR

    is_json = input_path.suffix.lower() == '.json'

    masking_dict = {
        "version": _cfg.__version__,
        "timestamp": datetime.now().isoformat(),
        "input_file": str(input_path),
        "statistics": {},
        "mappings": {k: {} for k in [
            "ipn", "passport_id", "military_id", "surname", "name",
            "military_unit", "order_number", "order_number_with_letters",
            "br_number", "br_number_slash", "br_number_complex",
            "rank", "brigade_number", "date", "date_text", "patronymic",
            "initials"
        ]},
        "instance_tracking": {}
    }
    instance_counters = {}

    # ================================================================
    # Read input
    # ================================================================
    print(f"Data Masking Script v{_cfg.__version__}")
    print(f"Processing {input_path}...")
    print(f"Output format: {'JSON' if is_json else 'TXT'}")
    if logger:
        logger.info(f"Processing {input_path}")

    input_data = _read_input(input_path, is_json, logger)
    if input_data is None:
        return EXIT_ERROR

    # ================================================================
    # Run masking pipeline
    # ================================================================
    masked_data, total_unique, chain = _run_masking(
        input_data, is_json, masking_dict, instance_counters,
        args, logger, timestamp, random_suffix
    )

    # ================================================================
    # Save results
    # ================================================================
    return _save_results(
        masked_data, is_json, masking_dict,
        output_path, map_path, report_path,
        total_unique, args, config, logger,
        chain=chain, password=password,
    )
