#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
CLI entry point and orchestration for data masking.

Extracted from data_masking.py during the package refactoring (v2.5.0).
"""

import json
import os
import re
import shutil
import sys
import random
import argparse
from pathlib import Path
from datetime import datetime
from typing import Any, Dict, List, Optional, Tuple

from datamasking._fsutil import atomic_write_private
from datamasking._textio import read_text, check_encoding_settings
from datamasking.masking import constants as _cfg
from datamasking.masking.helpers import validate_file_size

# Коди виходу: 0 — успіх, 1 — помилка виконання, 2 — помилка використання CLI
EXIT_OK = 0
EXIT_ERROR = 1
EXIT_USAGE = 2

# Єдина env-змінна для пароля (та сама на боці unmask)
PASSWORD_ENV_DEFAULT = "DATA_MASKING_PASSWORD"
from datamasking.masking.engine import (
    mask_text_context_aware, mask_json_recursive,
)

# ============================================================================
# OPTIONAL MODULES
# ============================================================================
import logging as _logging
_opt_logger = _logging.getLogger(__name__)

try:
    from datamasking.extras.selective import (
        get_available_types, get_types_help, create_filter, apply_filter_to_globals,
    )
    SELECTIVE_AVAILABLE = True
except ImportError:
    SELECTIVE_AVAILABLE = False
    _opt_logger.debug("datamasking.extras.selective not available — --only/--exclude disabled")

try:
    from datamasking.extras.re_mask import MappingChain, make_empty_masking_dict
    REMASK_AVAILABLE = True
except ImportError:
    REMASK_AVAILABLE = False
    _opt_logger.debug("datamasking.extras.re_mask not available — re-masking disabled")

try:
    from datamasking.extras.security import MappingSecurityManager, is_encryption_available
    SECURITY_AVAILABLE = True
except ImportError:
    SECURITY_AVAILABLE = False

    def is_encryption_available() -> bool:  # type: ignore[misc]
        return False
    _opt_logger.debug("datamasking.extras.security not available — encryption disabled")

try:
    from datamasking.extras.config import ConfigLoader, format_ignored_keys_warning, is_strict
    CONFIG_AVAILABLE = True
except ImportError:
    CONFIG_AVAILABLE = False
    _opt_logger.debug("datamasking.extras.config not available — YAML config disabled")

try:
    from datamasking.extras.masking_logger import setup_logging
    LOGGING_AVAILABLE = True
except ImportError:
    LOGGING_AVAILABLE = False
    _opt_logger.debug("datamasking.extras.masking_logger not available — structured logging disabled")

try:
    from datamasking.extras.password_generator import generate_password
    PASSWORD_GENERATOR_AVAILABLE = True
except ImportError:
    PASSWORD_GENERATOR_AVAILABLE = False
    _opt_logger.debug("datamasking.extras.password_generator not available — password generation disabled")


# ============================================================================
# UTILITY FUNCTIONS
# ============================================================================

def generate_default_config(output_path: str) -> None:
    """Generate a default config.yaml file.

    Єдине джерело шаблону — ConfigLoader (extras/config.py): раніше CLI мав
    власну копію, яка розходилась зі схемою loader-а
    (`security.password_generation: true` замість секції).
    """
    if CONFIG_AVAILABLE:
        ConfigLoader.generate_default_config(output_path)
        return
    config_content = f"""\
# Data Masking Configuration v{_cfg.__version__}
# Generated by data_masking.py

system:
  version: "v{_cfg.__version__}"
  hash_algorithm: "blake2b"
  preserve_case: true
  debug_mode: false

security:
  encrypt_output: false
  password_generation: true
  password_env_var: "DATA_MASKING_PASSWORD"
  password_length: 24

masking_rules:
  enable_ranks: true
  enable_names: true
  enable_ipn: true
  enable_passport: true
  enable_military_id: true
  enable_dates: true
  enable_brigades: true
  enable_units: true
  enable_orders: true
  enable_br_numbers: true

logging:
  level: "INFO"
  file: null
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

router_rules:
  default_action: "mask"
"""
    Path(output_path).write_text(config_content, encoding='utf-8')


def _password_settings(config) -> Tuple[str, bool, int]:
    """(назва змінної з паролем, чи можна генерувати, довжина) з конфігурації.

    Змінна: перша задана, відмінна від стандартної, з security.password_env_var,
    password_generation.env_var. Генерація дозволена, лише якщо жоден із
    security.auto_generate_password / security.password_generation.enabled /
    password_generation.enabled не false. Довжина — найбільша із
    security.password_length і password_generation.length (обох секцій):
    довший пароль ніколи не шкодить.
    """
    security = getattr(config, 'security', None)
    sec_gen = getattr(security, 'password_generation', None)
    top_gen = getattr(config, 'password_generation', None)

    env_name = PASSWORD_ENV_DEFAULT
    for candidate in (getattr(security, 'password_env_var', None), getattr(top_gen, 'env_var', None)):
        if candidate and str(candidate) != PASSWORD_ENV_DEFAULT:
            env_name = str(candidate)
            break

    allowed = all(flag is not False for flag in (
        getattr(security, 'auto_generate_password', True),
        getattr(sec_gen, 'enabled', True),
        getattr(top_gen, 'enabled', True),
    ))

    lengths = []
    for value in (getattr(security, 'password_length', 24), getattr(sec_gen, 'length', 24),
                  getattr(top_gen, 'length', 24)):
        try:
            if not isinstance(value, bool):
                lengths.append(int(value))
        except (TypeError, ValueError):
            pass
    length = max([n for n in lengths if 8 <= n <= 1024] or [24])
    return env_name, allowed, length


_PASSWORD_SPECIALS = "!@#$%^&*"


def _password_policy(config) -> Dict[str, Any]:
    """Склад згенерованого пароля з конфігурації.

    use_special_chars: false у будь-якій із секцій (security.password_generation
    або верхньорівнева password_generation) — без спецсимволів.
    min_*: мінімальна кількість символів класу (лише security.password_generation).
    Raises ValueError, якщо вимоги несумісні.
    """
    import string
    sec_gen = getattr(getattr(config, 'security', None), 'password_generation', None)
    top_gen = getattr(config, 'password_generation', None)
    length = _password_settings(config)[2] if config is not None else 24
    specials = all(getattr(g, 'use_special_chars', True) is not False for g in (sec_gen, top_gen))

    mins = {}
    for key in ("min_uppercase", "min_lowercase", "min_digits", "min_special"):
        mins[key] = _int_setting(getattr(sec_gen, key, 0) or 0,
                                 f"security.password_generation.{key}", 0, 1024)
    if mins["min_special"] and not specials:
        raise ValueError("security.password_generation.min_special needs use_special_chars: true")
    if sum(mins.values()) > length:
        raise ValueError(f"password_generation minimums ({sum(mins.values())} characters) "
                         f"exceed the password length ({length})")
    classes = [
        (string.ascii_uppercase, mins["min_uppercase"]),
        (string.ascii_lowercase, mins["min_lowercase"]),
        (string.digits, mins["min_digits"]),
    ]
    if specials:
        classes.append((_PASSWORD_SPECIALS, mins["min_special"]))
    return {"length": length, "classes": classes}


def generate_password_from_config(config) -> str:
    """Generate a secure password, optionally using config settings."""
    import secrets
    policy = _password_policy(config)
    alphabet = "".join(chars for chars, _ in policy["classes"])
    chars = [secrets.choice(c) for c, n in policy["classes"] for _ in range(n)]
    chars += [secrets.choice(alphabet) for _ in range(policy["length"] - len(chars))]
    secrets.SystemRandom().shuffle(chars)
    return "".join(chars)


def _build_parser() -> argparse.ArgumentParser:
    """Build and return the CLI argument parser."""
    parser = argparse.ArgumentParser(
        description=f"Data Masking Script v{_cfg.__version__}",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("-V", "--version", action="version",
                        version=f"%(prog)s {_cfg.__version__}")
    parser.add_argument("-i", "--input", default="input.txt", help="Input file")
    parser.add_argument("-o", "--output", help="Output file (mapping and report are written next to it)")
    parser.add_argument("--force", action="store_true",
                        help="Overwrite an existing output file")
    parser.add_argument("--no-report", action="store_true", help="No report")
    parser.add_argument("--debug", action="store_true", help="Debug mode")
    parser.add_argument("--init-config", action="store_true",
                        help="Generate default config.yaml and exit")
    parser.add_argument("--config", type=str, default=None,
                        help="Path to YAML configuration file")
    parser.add_argument("--config-local", type=str, default=None, metavar="FILE",
                        help="Private overrides on top of the configuration (default: "
                             "config_local.yaml next to it and in the user config directory)")
    parser.add_argument("--no-local-config", action="store_true",
                        help="Ignore config_local.yaml files")
    parser.add_argument("--list-exclusions", action="store_true",
                        help="Show the words, phrases and legal acts excluded from masking "
                             "(built-in + configuration), then exit")
    parser.add_argument("--log-level", type=str, default=None,
                        choices=["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"],
                        help="Logging level")
    parser.add_argument("--log-file", type=str, default=None,
                        help="Path to log file")

    if SELECTIVE_AVAILABLE:
        parser.add_argument("--only", nargs="+", metavar="TYPE",
                            help="Mask only these types (space- or comma-separated; "
                                 "groups and aliases accepted, see --list-types)")
        parser.add_argument("--exclude", nargs="+", metavar="TYPE",
                            help="Mask everything except these types")
        parser.add_argument("--list-types", action="store_true",
                            help="List available masking types, groups and aliases, then exit")

    if SECURITY_AVAILABLE:
        parser.add_argument("--encrypt", action="store_true",
                            help="Encrypt the mapping file")
        parser.add_argument("--password", type=str, default=None,
                            help="Password for encryption (visible in process list; "
                                 "prefer --password-env)")
        parser.add_argument("--password-env", type=str, default=None, metavar="VAR",
                            help=f"Environment variable holding the password "
                                 f"(default lookup: {PASSWORD_ENV_DEFAULT})")

    if REMASK_AVAILABLE:
        parser.add_argument("--re-mask", type=int, default=None, metavar="N",
                            help="Number of re-masking passes (2-10)")

    return parser


def _load_config(args) -> Tuple[Optional[Any], Optional[str]]:
    """Load configuration: YAML (якщо є) + ENV-перекриття.

    Раніше без config.yaml loader узагалі не запускався, і всі
    DATA_MASKING_* змінні мовчки ігнорувались; битий YAML давав дефолти
    з написом «Loaded config». Тепер: loader працює завжди (ENV діє без
    файлу), помилка читання/розбору явно вказаного або наявного файлу —
    фатальна для CLI.

    Returns:
        (config, None) або (None, error_message)
    """
    if not CONFIG_AVAILABLE:
        return None, None

    config_path = args.config
    if config_path is not None and not Path(config_path).exists():
        return None, f"Config file not found: {config_path}"

    try:
        loader = ConfigLoader(config_path, local_path=getattr(args, 'config_local', None),
                              use_local=not getattr(args, 'no_local_config', False))
        config = loader.load()
    except (FileNotFoundError, PermissionError, ValueError, OSError) as e:
        return None, f"Could not load config: {e}"

    source = loader.loaded_from
    if source:
        print(f"Loaded config from {source}")
    for local in loader.local_loaded:
        print(f"Loaded local config from {local}")
    for notice in loader.notices:
        print(notice, file=sys.stderr)
    for ignored_source, keys in loader.ignored_by_source:
        warning = format_ignored_keys_warning(ignored_source, keys)
        if is_strict(config):
            return None, "strict_mode: " + warning.replace("Warning: ", "", 1)
        print(warning, file=sys.stderr)
    if loader.local_loaded:
        source = ", ".join(([source] if source else []) + loader.local_loaded)
    try:
        setattr(config, "_source", source)  # для звіту; dataclass дозволяє атрибут
    except AttributeError:
        pass
    return config, None


def _setup_logger(args, config) -> Optional[Any]:
    """Set up structured logging."""
    if not LOGGING_AVAILABLE:
        return None

    log_level = args.log_level
    log_file = args.log_file
    log_cfg = getattr(config, 'logging', None) if config is not None else None
    cli_logging = log_level is not None or log_file is not None

    # logging.enabled: false — структурований лог вимкнено (прапорці CLI
    # --log-level / --log-file все одно вмикають його на цей запуск)
    if getattr(log_cfg, 'enabled', True) is False and not cli_logging:
        return None

    if log_cfg is not None:
        if log_level is None:
            log_level = getattr(log_cfg, 'level', None)
        if log_file is None:
            to_file = getattr(log_cfg, 'log_to_file', None)
            cfg_file = getattr(log_cfg, 'file', None)
            if to_file is not False:
                log_file = cfg_file
            if to_file is True and not cfg_file:
                _config_warning(args, "logging.log_to_file is true but logging.file is not set — "
                                      "logging to the console only")

    if log_level is None:
        log_level = "INFO"
    console = getattr(log_cfg, 'log_to_console', True) is not False

    # logging.format (рядок у файлі логу), max_log_size_mb + log_rotation_count
    file_format = getattr(log_cfg, 'format', None) or None
    if file_format:
        import logging as _std_logging
        try:
            _std_logging.Formatter(file_format, validate=True)
        except (ValueError, TypeError) as e:
            _config_warning(args, f"logging.format is invalid ({e}) — using the default format")
            file_format = None
    max_bytes, backup_count = 0, 5
    size_mb = getattr(log_cfg, 'max_log_size_mb', None)
    if size_mb is not None:
        try:
            max_bytes = _int_setting(size_mb, "logging.max_log_size_mb", 1, 100_000) * 1024 * 1024
            backup_count = _int_setting(getattr(log_cfg, 'log_rotation_count', 5),
                                        "logging.log_rotation_count", 0, 1000)
        except ValueError as e:
            _config_warning(args, f"{e} — log rotation disabled")
            max_bytes = 0

    try:
        logger = setup_logging(level=log_level, log_file=log_file, console=console,
                               file_format=file_format, max_bytes=max_bytes,
                               backup_count=backup_count)
        logger.info(f"Data Masking Script v{_cfg.__version__} started")
        return logger
    except (ValueError, OSError, TypeError) as e:
        print(f"Warning: could not setup logging: {e}")
        return None


def _apply_selective_filters(args, logger) -> Optional[str]:
    """Apply --only / --exclude selective masking filters.

    Розбір імен типів делеговано extras.selective (канонічні імена,
    множина, українські форми, групи, кома/пробіл як роздільник) — раніше
    CLI мав власну несумісну таблицю, і невідомий тип тихо давав
    «замасковано нічого» з exit 0.

    Returns:
        None — ок; рядок з помилкою — невідомий тип (виклик має завершити
        роботу з EXIT_USAGE, НЕ записавши жодного файлу).
    """
    if not SELECTIVE_AVAILABLE:
        return None

    only_types = getattr(args, 'only', None)
    exclude_types = getattr(args, 'exclude', None)

    if not only_types and not exclude_types:
        return None

    if only_types and exclude_types:
        return "--only and --exclude cannot be combined"

    only_str = " ".join(only_types) if only_types else None
    exclude_str = " ".join(exclude_types) if exclude_types else None
    try:
        selective_filter = create_filter(only=only_str, exclude=exclude_str)
    except ValueError as e:
        if logger:
            logger.error(f"Selective masking: {e}")
        return str(e)

    if not selective_filter.enabled_types:
        return "Selective masking would disable every type — nothing to do"

    apply_filter_to_globals(selective_filter, vars(_cfg))

    mode = "--only" if only_types else "--exclude"
    source = getattr(args, '_selective_source', None)
    if source:
        mode = f"{source} ({mode})"
    enabled = ", ".join(selective_filter.get_enabled_list())
    print(f"Selective masking: {mode} {only_str or exclude_str} → enabled: {enabled}")
    if logger:
        logger.info(f"Selective masking: {mode} {only_str or exclude_str} → enabled: {enabled}")
    return None


def _config_warning(args, message: str) -> None:
    """Попередження конфігурації; у суворому режимі — помилка (main
    завершує роботу з кодом 1 до запису файлів)."""
    if getattr(args, '_strict', False):
        args._strict_errors = getattr(args, '_strict_errors', []) + [message]
    else:
        print(f"Warning: {message}", file=sys.stderr)


def _selective_from_config(args, config) -> Optional[str]:
    """router_rules.only_types / skip_types → як --only / --exclude.

    Діє, лише якщо в CLI немає ні --only, ні --exclude (CLI пріоритетніший).
    Як і в CLI, разом не поєднуються. Повертає помилку або None.
    """
    router = getattr(config, 'router_rules', None) if config is not None else None
    if router is None or getattr(args, 'only', None) or getattr(args, 'exclude', None):
        return None

    def as_list(name: str) -> Tuple[Optional[List[str]], Optional[str]]:
        value = getattr(router, name, None)
        if value in (None, "", []):
            return None, None
        if isinstance(value, str):
            value = [value]
        if not isinstance(value, list) or not all(isinstance(v, str) for v in value):
            return None, f"router_rules.{name} must be a list of type names, got {value!r}"
        return list(value), None

    only, err = as_list('only_types')
    if err:
        return err
    skip, err = as_list('skip_types')
    if err:
        return err
    if only and skip:
        return "router_rules.only_types and router_rules.skip_types cannot be combined"
    if only:
        args.only, args._selective_source = only, "router_rules.only_types"
    elif skip:
        args.exclude, args._selective_source = skip, "router_rules.skip_types"
    return None


def _major(version: str) -> Optional[int]:
    m = re.match(r"^\s*v?(\d+)", str(version or ""))
    return int(m.group(1)) if m else None


def _int_setting(value, name: str, lo: int, hi: int) -> int:
    """Ціле в межах [lo, hi]; інакше ValueError з текстом для користувача."""
    if isinstance(value, bool):
        raise ValueError(f"{name} must be an integer, got {value!r}")
    try:
        n = int(value)
    except (TypeError, ValueError):
        raise ValueError(f"{name} must be an integer, got {value!r}") from None
    if not lo <= n <= hi:
        raise ValueError(f"{name} must be between {lo} and {hi}, got {n}")
    return n


def _apply_level1_settings(args, config, logger) -> Optional[str]:
    """Опції рівня 1 (v3.0.27): аліаси, межі дат, перемикачі, перевірки
    значень. Повертає помилку конфігурації або None."""
    try:
        return _apply_level1_settings_impl(args, config, logger)
    except ValueError as e:
        return str(e)


def _apply_level1_settings_impl(args, config, logger) -> Optional[str]:
    system = getattr(config, 'system', None)
    rules = getattr(config, 'masking_rules', None)
    validation = getattr(config, 'validation', None)
    security = getattr(config, 'security', None)
    remask = getattr(config, 'remask', None)

    # system.version — файл для новішої мажорної версії програми
    cfg_version = getattr(system, 'version', '')
    cfg_major, prog_major = _major(cfg_version), _major(_cfg.__version__)
    if cfg_major is not None and prog_major is not None and cfg_major > prog_major:
        _config_warning(args, f"config is for version {cfg_version}, this program is "
                              f"{_cfg.__version__}; some options may not be understood")

    # Ключі з єдиним підтримуваним значенням
    checks = [
        (getattr(security, 'encryption_algorithm', None), "security.encryption_algorithm", ("AES-256-GCM",)),
        (getattr(getattr(security, 'password_generation', None), 'algorithm', None),
         "security.password_generation.algorithm", ("secrets",)),
        (getattr(remask, 'chain_format', None), "remask.chain_format", ("json",)),
    ]
    for value, name, allowed in checks:
        if value is not None and str(value).strip().lower() not in {a.lower() for a in allowed}:
            return f"{name}: only {', '.join(allowed)} is supported, got {value!r}"

    # Незмінна поведінка: приймається лише true
    from datamasking.extras.config import ALWAYS_ON_KEYS
    for dotted, reason in ALWAYS_ON_KEYS.items():
        section, key = dotted.split('.')
        value = getattr(getattr(config, section, None), key, True)
        if value is not True:
            return f"{dotted}: only true is supported, got {value!r} ({reason})"

    # masking_rules.preserve_case — перекриває system.preserve_case
    rules_case = getattr(rules, 'preserve_case', None)
    if rules_case is not None:
        _cfg.PRESERVE_CASE = bool(rules_case)

    # Ліміт розміру: діє менший із system.max_file_size_mb і validation.max_input_size_mb
    sys_mb = getattr(system, 'max_file_size_mb', None)
    if sys_mb is not None:
        limit_mb = _int_setting(sys_mb, "system.max_file_size_mb", 1, 1_000_000)
        _cfg.MAX_INPUT_FILE_SIZE = min(_cfg.MAX_INPUT_FILE_SIZE, limit_mb * 1024 * 1024)

    # Межі розпізнавання дат
    if validation is not None:
        if getattr(validation, 'validate_date_range', True) is False:
            _cfg.DATE_DETECT_YEAR_MIN, _cfg.DATE_DETECT_YEAR_MAX = 1, 9999
        else:
            lo = _int_setting(getattr(validation, 'min_date_year', 1900), "validation.min_date_year", 1, 9999)
            hi = _int_setting(getattr(validation, 'max_date_year', 2100), "validation.max_date_year", 1, 9999)
            if lo > hi:
                return f"validation.min_date_year ({lo}) is greater than validation.max_date_year ({hi})"
            _cfg.DATE_DETECT_YEAR_MIN, _cfg.DATE_DETECT_YEAR_MAX = lo, hi

    # Склеювання розірваних звань
    line_fix = getattr(rules, 'rank_line_break_fix', None)
    if line_fix is not None:
        _cfg.RANK_LINE_BREAK_FIX = bool(line_fix)

    # Текстові дати, прізвища, по батькові, номери документів: окремо або
    # «як відповідний загальний прапорець»
    if not getattr(args, 'only', None) and not getattr(args, 'exclude', None):
        def follow(key: str, base: bool) -> bool:
            value = getattr(rules, key, None)
            return base if value is None else bool(value)
        _cfg.MASK_DATE_TEXT = follow('enable_date_text', _cfg.MASK_DATES)
        _cfg.MASK_SURNAMES = follow('enable_surnames', _cfg.MASK_NAMES)
        _cfg.MASK_PATRONYMICS = follow('enable_patronymics', _cfg.MASK_NAMES)
        _cfg.MASK_DOCUMENT_NUMBERS = follow('enable_document_numbers', _cfg.MASK_ORDERS)

    # Перемаскування
    if remask is not None:
        if getattr(remask, 'enabled', True) is False and getattr(args, 're_mask', None):
            return "--re-mask is disabled by the configuration (remask.enabled: false)"
        _cfg.REMASK_MAX_PASSES = _int_setting(getattr(remask, 'max_passes', 10), "remask.max_passes", 2, 10)

    # Склад пароля — перевірити ДО запису файлів (сам пароль генерується пізніше)
    _password_policy(config)

    # Кодування вхідного файлу
    enc, allowed_list = check_encoding_settings(
        getattr(system, 'encoding', 'utf-8'),
        getattr(validation, 'allowed_encodings', None))
    _cfg.INPUT_ENCODING, _cfg.ALLOWED_ENCODINGS = enc, tuple(allowed_list)

    # Дайджест хешу (лише blake2b) і контрольна сума ІПН
    digest = getattr(system, 'hash_digest_size', None)
    if digest is not None:
        digest = _int_setting(digest, "system.hash_digest_size", 1, 64)
        if digest != 64 and str(_cfg.HASH_ALGORITHM).lower() != "blake2b":
            raise ValueError(f"system.hash_digest_size applies to blake2b only "
                             f"(hash_algorithm is {_cfg.HASH_ALGORITHM})")
        _cfg.HASH_DIGEST_SIZE = digest
    _cfg.VALIDATE_IPN_CHECKSUM = getattr(validation, 'validate_ipn_checksum', False) is True

    # Розпізнавання ПІБ
    min_len = getattr(validation, 'min_name_length', None)
    if min_len is not None:
        _cfg.NAME_MIN_LENGTH = _int_setting(min_len, "validation.min_name_length", 1, 100)
    max_len = getattr(validation, 'max_name_length', None)
    if max_len is not None:
        _cfg.NAME_MAX_LENGTH = _int_setting(max_len, "validation.max_name_length", 1, 1000)
        if _cfg.NAME_MAX_LENGTH < _cfg.NAME_MIN_LENGTH:
            raise ValueError(f"validation.max_name_length ({_cfg.NAME_MAX_LENGTH}) is less than "
                             f"min_name_length ({_cfg.NAME_MIN_LENGTH})")
    if getattr(validation, 'allow_abbreviated_patronymic', True) is False:
        _cfg.ALLOW_ABBREVIATED_PATRONYMIC = False
        print("Warning: validation.allow_abbreviated_patronymic is false — initials "
              "(\"Іванов І.І.\") are NOT masked; the surname only when it follows a rank",
              file=sys.stderr)
    if getattr(validation, 'strict_pib_format', False) is True:
        _cfg.STRICT_PIB_FORMAT = True
        print("Warning: validation.strict_pib_format is true — only full three-word names "
              "are masked; a surname alone or two words stay open", file=sys.stderr)

    # Рід масок імен (preserve_gender: false — не видавати стать)
    _cfg.PRESERVE_GENDER = getattr(rules, 'preserve_gender', True) is not False
    if not _cfg.PRESERVE_GENDER:
        print("Note: masking_rules.preserve_gender is false — first names and patronymics get a "
              "random gender; surname endings (-ова), feminine ranks and verbs can still reveal it",
              file=sys.stderr)

    # Власні шаблони і порядок фаз
    from datamasking.masking import custom as _custom
    router = getattr(config, 'router_rules', None)
    _cfg.CUSTOM_PATTERNS = _custom.compile_patterns(getattr(rules, 'custom_patterns', None),
                                                    getattr(router, 'default_action', 'mask'))

    # Виключення: вбудовані переліки + exclusions (фрази — як custom skip,
    # always_mask — як custom mask, після власних шаблонів)
    from datamasking.masking import exclusions as _exclusions
    excl = _exclusions.build(getattr(config, 'exclusions', None),
                             getattr(config, 'dictionaries', None))
    _cfg.ABBREVIATION_WHITELIST = excl.abbreviations
    _cfg.EXCLUDE_WORDS_LOWER = excl.words_lower
    _cfg.LEGAL_ACT_DATE_PREFIX = excl.legal_act_prefix
    _cfg.CUSTOM_PATTERNS = excl.skip_patterns + _cfg.CUSTOM_PATTERNS + excl.mask_patterns
    args._exclusions = excl
    _cfg.PROCESSING_ORDER = _custom.build_processing_order(
        getattr(router, 'processing_order', None), getattr(router, 'priority_overrides', None),
        _cfg.DEFAULT_PROCESSING_ORDER)

    # Виведення ключа для .enc (перевірка — до запису файлів)
    kdf = {
        "kdf": getattr(security, 'key_derivation', 'pbkdf2'),
        "n": getattr(security, 'scrypt_n', 16384),
        "r": getattr(security, 'scrypt_r', 8),
        "p": getattr(security, 'scrypt_p', 1),
        "salt_length": getattr(security, 'salt_length', 16),
    }
    if SECURITY_AVAILABLE:
        args._kdf = MappingSecurityManager.check_kdf(kdf)

    # Тимчасові файли
    temp_dir = str(getattr(system, 'temp_dir', '') or '')
    if temp_dir:
        if not Path(temp_dir).is_dir():
            raise ValueError(f"system.temp_dir {temp_dir!r} is not an existing directory")
        import tempfile
        tempfile.tempdir = temp_dir
    from datamasking import _fsutil
    _fsutil.SECURE_DELETE_TEMP = getattr(security, 'secure_delete_temp', True) is not False

    log_cfg = getattr(config, 'logging', None)
    _cfg.LOG_SENSITIVE_DATA = getattr(log_cfg, 'log_sensitive_data', False) is True
    _cfg.LOG_PERFORMANCE = getattr(log_cfg, 'log_performance', False) is True
    return None


def _apply_config_settings(args, config, logger) -> Optional[str]:
    """Apply config-based masking rules and system settings.

    Returns an error message (fatal for the CLI) or None.
    """
    if config is None:
        return None

    # Masking rules from config (only if --only/--exclude not specified)
    masking_rules = getattr(config, 'masking_rules', None)
    if masking_rules is not None:
        only_types = getattr(args, 'only', None) if SELECTIVE_AVAILABLE else None
        exclude_types = getattr(args, 'exclude', None) if SELECTIVE_AVAILABLE else None

        if not only_types and not exclude_types:
            config_rules_map = {
                'enable_ranks': 'MASK_RANKS',
                'enable_names': 'MASK_NAMES',
                'enable_ipn': 'MASK_IPN',
                'enable_passport': 'MASK_PASSPORT',
                'enable_military_id': 'MASK_MILITARY_ID',
                'enable_dates': 'MASK_DATES',
                'enable_brigades': 'MASK_BRIGADES',
                'enable_units': 'MASK_UNITS',
                'enable_orders': 'MASK_ORDERS',
                'enable_br_numbers': 'MASK_BR_NUMBERS',
            }
            for config_key, global_var in config_rules_map.items():
                value = getattr(masking_rules, config_key, None)
                if value is not None:
                    setattr(_cfg, global_var, bool(value))
                    if logger:
                        logger.debug(f"Config: {config_key} = {value}")

    # System settings from config
    system_cfg = getattr(config, 'system', None)
    if system_cfg is not None:
        cfg_debug = getattr(system_cfg, 'debug_mode', None)
        if cfg_debug is not None and not args.debug:
            _cfg.DEBUG_MODE = bool(cfg_debug)

        cfg_preserve_case = getattr(system_cfg, 'preserve_case', None)
        if cfg_preserve_case is not None:
            _cfg.PRESERVE_CASE = bool(cfg_preserve_case)

        cfg_hash = getattr(system_cfg, 'hash_algorithm', None)
        if cfg_hash is not None:
            _cfg.HASH_ALGORITHM = str(cfg_hash)

        # system.faker_locale — словники faker для синтетичних прізвищ/імен
        locale = getattr(system_cfg, 'faker_locale', None)
        if locale and locale != _cfg.FAKER_LOCALE:
            try:
                _cfg.set_faker_locale(str(locale))
            except ValueError as e:
                return str(e)
            if logger:
                logger.info(f"Faker locale: {locale}")

    # masking_rules.surname_prefix_length — скільки символів оригіналу лишати
    prefix_len = getattr(masking_rules, 'surname_prefix_length', None)
    if prefix_len is not None:
        try:
            prefix_len = int(prefix_len)
        except (TypeError, ValueError):
            return f"masking_rules.surname_prefix_length must be an integer, got {prefix_len!r}"
        if prefix_len < 0:
            return "masking_rules.surname_prefix_length must be >= 0"
        _cfg.SURNAME_PREFIX_LENGTH = prefix_len

    # validation.max_input_size_mb — раніше документований, але мертвий ключ
    validation_cfg = getattr(config, 'validation', None)
    max_mb = getattr(validation_cfg, 'max_input_size_mb', None)
    if isinstance(max_mb, int) and max_mb > 0:
        _cfg.MAX_INPUT_FILE_SIZE = max_mb * 1024 * 1024

    # security.encrypt_output — те саме, що --encrypt (раніше ігнорувався)
    security_cfg = getattr(config, 'security', None)
    if getattr(security_cfg, 'encrypt_output', False) and hasattr(args, 'encrypt') and not args.encrypt:
        args.encrypt = True
        if logger:
            logger.info("Encryption enabled by config (security.encrypt_output)")
    return _apply_level1_settings(args, config, logger)


def _prepare_output_paths(args, input_path: Path) -> Tuple[Path, Path, Path, str, int]:
    """Determine output, mapping, and report file paths.

    Mapping і звіт лягають ПОРУЧ із вихідним файлом (раніше — завжди у cwd,
    тож при `-o dir/x.txt` unmask не знаходив пару).
    """
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    is_json = input_path.suffix.lower() == '.json'
    ext = '.json' if is_json else '.txt'

    # Суфікс перекидаємо, поки набір імен не унікальний: два запуски в одну
    # секунду раніше могли мовчки перезаписати файли одне одного (p≈1/900)
    for _ in range(50):
        random_suffix = random.randint(100, 999)
        output_path = Path(args.output) if args.output else Path(f"output_{timestamp}_{random_suffix}{ext}")
        out_dir = output_path.parent
        map_path = out_dir / f"masking_map_{timestamp}_{random_suffix}.json"
        report_path = out_dir / f"masking_report_{timestamp}_{random_suffix}.txt"
        clashes = [map_path, map_path.with_suffix('.enc'), report_path]
        if not args.output:
            clashes.append(output_path)
        if not any(p.exists() for p in clashes):
            break

    return output_path, map_path, report_path, timestamp, random_suffix


def _validate_output_paths(args, input_path: Path, output_path: Path) -> Optional[str]:
    """Захист від втрати даних: -o не може вказувати на вхід і не
    перезаписує існуючий файл без --force. Повертає текст помилки або None."""
    try:
        same = output_path.resolve() == input_path.resolve()
    except OSError:
        same = False
    if same:
        return f"Output file must differ from input file: {output_path}"
    if output_path.exists() and not getattr(args, 'force', False):
        return f"Output file already exists: {output_path} (use --force to overwrite)"
    return None


def _resolve_password(args, config, logger) -> Tuple[Optional[str], Optional[str]]:
    """Визначає пароль для --encrypt ДО запису будь-яких файлів.

    Пріоритет: --password → --password-env VAR → $DATA_MASKING_PASSWORD →
    згенерований (показується один раз у stderr).
    Явно вказана, але порожня/відсутня змінна — помилка, а не мовчазна
    підміна випадковим паролем.

    Returns:
        (password, None) або (None, error_message)
    """
    password = getattr(args, 'password', None)
    if password is not None:
        if not password:
            return None, "--password must not be empty"
        return password, None

    password_env = getattr(args, 'password_env', None)
    if password_env:
        password = os.environ.get(password_env)
        if not password:
            return None, f"Environment variable '{password_env}' is not set or empty"
        return password, None

    env_name, generation_allowed, _length = _password_settings(config)
    password = os.environ.get(env_name)
    if password:
        if logger:
            logger.info(f"Password taken from ${env_name}")
        return password, None

    if not generation_allowed:
        return None, (f"--encrypt needs a password: set ${env_name}, use --password-env VAR, "
                      f"or allow generation (security.auto_generate_password)")

    password_file = str(getattr(getattr(config, 'security', None), 'password_file', '') or '')
    if password_file:
        target = Path(password_file)
        if target.exists() and not getattr(args, 'force', False):
            return None, f"security.password_file {target} already exists (use --force to overwrite)"
        args._password_file = target

    password = generate_password_from_config(config)
    _print_generated_password(password, getattr(args, '_password_file', None))
    return password, None


def _read_input(input_path: Path, is_json: bool, logger, masking_dict: Optional[Dict] = None):
    """Read input file (JSON or text) in system.encoding (or detected: auto).

    Використане кодування запам'ятовується в masking_dict["input_encoding"]
    (якщо не utf-8): вихід пишеться ним же, а unmask читає й пише ним же.
    """
    try:
        validate_file_size(input_path, _cfg.MAX_INPUT_FILE_SIZE)
        text, used = read_text(input_path, _cfg.INPUT_ENCODING, _cfg.ALLOWED_ENCODINGS)
        if used != "utf-8":
            print(f"Input encoding: {used}" + (" (auto)" if _cfg.INPUT_ENCODING == "auto" else ""))
            if masking_dict is not None:
                masking_dict["input_encoding"] = used
        if logger:
            logger.info(f"Input encoding: {used}")
        return json.loads(text) if is_json else text
    except (FileNotFoundError, PermissionError, OSError, json.JSONDecodeError,
            UnicodeDecodeError, ValueError) as e:
        print(f"Error reading file: {e}")
        if logger:
            logger.error(f"Error reading file: {e}")
        return None


def _run_masking(input_data, is_json: bool, masking_dict: Dict,
                 instance_counters: Dict, args, logger,
                 timestamp: str, random_suffix: int) -> Tuple[Any, int, Optional[Any]]:
    """Execute single-pass or multi-pass masking.

    Returns:
        (masked_data, total_unique, chain) — chain є лише у multi-pass
        режимі; його збереження (і шифрування) робить _save_results.
    """
    re_mask_passes = getattr(args, 're_mask', None)

    if re_mask_passes is not None:
        if re_mask_passes < 2:
            print("Warning: --re-mask requires at least 2 passes, using single-pass mode")
            if logger:
                logger.warning("--re-mask value < 2, falling back to single-pass")
            re_mask_passes = None
        elif re_mask_passes > _cfg.REMASK_MAX_PASSES:
            cap = _cfg.REMASK_MAX_PASSES
            print(f"Warning: --re-mask capped at {cap} passes (was {re_mask_passes})")
            if logger:
                logger.warning(f"--re-mask capped at {cap} (requested {re_mask_passes})")
            re_mask_passes = cap

    if REMASK_AVAILABLE and re_mask_passes and re_mask_passes > 1:
        return _run_multi_pass_masking(
            input_data, is_json, masking_dict, args, logger,
            re_mask_passes, timestamp, random_suffix
        )
    else:
        masked_data, total_unique = _run_single_pass_masking(
            input_data, is_json, masking_dict, instance_counters, logger
        )
        return masked_data, total_unique, None


def _run_multi_pass_masking(input_data, is_json: bool, masking_dict: Dict,
                            args, logger, re_mask_passes: int,
                            timestamp: str, random_suffix: int) -> Tuple[Any, int, Any]:
    """Execute multi-pass re-masking with chain tracking.

    Chain НЕ зберігається тут — _save_results запише його (plaintext або
    .enc при --encrypt) поруч із вихідним файлом.
    """
    if logger:
        logger.info(f"Starting multi-pass re-masking ({re_mask_passes} passes)")

    chain = MappingChain()
    masked_data = input_data

    for pass_num in range(1, re_mask_passes + 1):
        print(f"  Прохід {pass_num}/{re_mask_passes}...")
        if logger:
            logger.info(f"Re-masking pass {pass_num}/{re_mask_passes}")

        pass_dict = make_empty_masking_dict(_cfg.__version__)
        pass_counters: Dict[str, int] = {}

        if is_json:
            masked_data = mask_json_recursive(masked_data, pass_dict, pass_counters)
        else:
            masked_data = mask_text_context_aware(masked_data, pass_dict, pass_counters)

        pass_dict["instance_tracking"] = pass_counters
        for category, mappings in pass_dict["mappings"].items():
            pass_dict["statistics"][category] = len(mappings)
        chain.add_pass(pass_dict)

    masking_dict["instance_tracking"] = {}
    total_unique = 0
    for p in chain.passes:
        for cat, count in p.get("statistics", {}).items():
            masking_dict["statistics"][cat] = masking_dict["statistics"].get(cat, 0) + count
            if cat != "total_masked":
                total_unique += count
    masking_dict["statistics"]["total_masked"] = total_unique

    return masked_data, total_unique, chain


def _run_single_pass_masking(input_data, is_json: bool, masking_dict: Dict,
                             instance_counters: Dict, logger) -> Tuple[Any, int]:
    """Execute single-pass masking."""
    if logger:
        logger.info("Starting single-pass masking")

    if is_json:
        masked_data = mask_json_recursive(input_data, masking_dict, instance_counters)
    else:
        masked_data = mask_text_context_aware(input_data, masking_dict, instance_counters)

    masking_dict["instance_tracking"] = instance_counters

    total_unique = 0
    for category, mappings in masking_dict["mappings"].items():
        count = len(mappings)
        masking_dict["statistics"][category] = count
        total_unique += count
    masking_dict["statistics"]["total_masked"] = total_unique

    return masked_data, total_unique


def _print_generated_password(password: str, saved_to: Optional[Path] = None) -> None:
    """Показує згенерований пароль у stderr (не stdout), щоб він не
    потрапляв у перенаправлений вивід, пайпи та логи CI."""
    import sys
    if saved_to:
        print(f"  Generated password (also saved to {saved_to}, mode 0600):", file=sys.stderr)
    else:
        print("  Generated password (shown once, NOT saved anywhere):", file=sys.stderr)
    print(f"  {password}", file=sys.stderr)


def _write_mapping(mapping: Dict, json_path: Path, password: Optional[str],
                   logger, kdf: Optional[Dict] = None) -> Path:
    """Записує mapping (звичайний або chain) — ОДИН файл.

    Без пароля: plaintext JSON (атомарно, 0600).
    З паролем: лише .enc — plaintext на диск не потрапляє взагалі
    (раніше --encrypt писав .json І .enc поруч).
    """
    if password:
        enc_path = json_path.with_suffix('.enc')
        MappingSecurityManager().encrypt_mapping(mapping, password, enc_path, kdf=kdf)
        if logger:
            logger.info(f"Mapping encrypted to {enc_path}")
        return enc_path

    payload = json.dumps(mapping, ensure_ascii=False, indent=2).encode("utf-8")
    atomic_write_private(json_path, payload)
    return json_path


def _write_report(report_path: Path, masking_dict: Dict, input_path: Path,
                  output_path: Path, is_json: bool, total_unique: int,
                  re_mask_passes, args, config) -> None:
    """Generate the detailed masking report file."""
    with open(report_path, 'w', encoding='utf-8') as f:
        f.write("=" * 60 + "\n")
        f.write("ЗВІТ МАСКУВАННЯ ДАНИХ\n")
        f.write("=" * 60 + "\n\n")
        f.write(f"Версія: {_cfg.__version__}\n")
        f.write(f"Дата та час: {masking_dict['timestamp']}\n")
        f.write(f"Вхідний файл: {input_path}\n")
        f.write(f"Вихідний файл: {output_path}\n")
        f.write(f"Формат: {'JSON' if is_json else 'TXT'}\n")

        f.write("\n" + "-" * 60 + "\n")
        f.write("КОНФІГУРАЦІЯ МАСКУВАННЯ\n")
        f.write("-" * 60 + "\n\n")
        f.write(f"  Прізвища (MASK_SURNAMES): {_cfg.MASK_SURNAMES}\n")
        f.write(f"  Імена (MASK_NAMES): {_cfg.MASK_NAMES}\n")
        f.write(f"  По батькові (MASK_PATRONYMICS): {_cfg.MASK_PATRONYMICS}\n")
        f.write(f"  ІПН (MASK_IPN): {_cfg.MASK_IPN}\n")
        f.write(f"  Паспорти (MASK_PASSPORT): {_cfg.MASK_PASSPORT}\n")
        f.write(f"  Військові ID (MASK_MILITARY_ID): {_cfg.MASK_MILITARY_ID}\n")
        f.write(f"  Звання (MASK_RANKS): {_cfg.MASK_RANKS}\n")
        f.write(f"  Бригади (MASK_BRIGADES): {_cfg.MASK_BRIGADES}\n")
        f.write(f"  Частини (MASK_UNITS): {_cfg.MASK_UNITS}\n")
        f.write(f"  Накази (MASK_ORDERS): {_cfg.MASK_ORDERS}\n")
        f.write(f"  Номери документів (MASK_DOCUMENT_NUMBERS): {_cfg.MASK_DOCUMENT_NUMBERS}\n")
        f.write(f"  БР номери (MASK_BR_NUMBERS): {_cfg.MASK_BR_NUMBERS}\n")
        f.write(f"  Дати (MASK_DATES): {_cfg.MASK_DATES}\n")
        f.write(f"  Збереження регістру (PRESERVE_CASE): {_cfg.PRESERVE_CASE}\n")
        f.write(f"  Алгоритм хешування: {_cfg.HASH_ALGORITHM}\n")

        if re_mask_passes and re_mask_passes > 1:
            f.write(f"\n  Режим: повторне маскування ({re_mask_passes} проходів)\n")
        else:
            f.write(f"\n  Режим: одинарне маскування\n")

        config_source = getattr(config, '_source', None)
        if config_source:
            f.write(f"  Конфігурація: {config_source}\n")

        f.write("\n" + "-" * 60 + "\n")
        f.write("СТАТИСТИКА МАСКУВАННЯ\n")
        f.write("-" * 60 + "\n\n")
        f.write(f"Загальна кількість УНІКАЛЬНИХ замаскованих елементів: {total_unique}\n\n")

        for key, value in sorted(masking_dict["statistics"].items()):
            if key != "total_masked" and value > 0:
                f.write(f"  • {key}: {value} (унікальних оригіналів)\n")

        f.write("\n" + "=" * 60 + "\n")
        f.write("СТАТИСТИКА ВХОДЖЕНЬ (Instance Tracking)\n")
        f.write("-" * 60 + "\n\n")

        sorted_report_instances = sorted(
            masking_dict["instance_tracking"].items(),
            key=lambda x: x[1],
            reverse=True
        )
        for masked_val, count in sorted_report_instances:
            f.write(f"  • '{masked_val}': {count} входжень\n")

        f.write("\n" + "=" * 60 + "\n")
        f.write(f"Кінець звіту. Всього записів у instance tracking: "
                f"{len(masking_dict['instance_tracking'])}\n")
        f.write("=" * 60 + "\n")


def _print_statistics(masking_dict: Dict, total_unique: int) -> None:
    print(f"📊 Статистика:")
    print(f"   Загальна кількість УНІКАЛЬНИХ замаскованих елементів: {total_unique}")
    for key, value in sorted(masking_dict["statistics"].items()):
        if key != "total_masked" and value > 0:
            print(f"   • {key}: {value} (унікальних оригіналів)")
    print()
    print(f"   Статистика входжень (Instance Tracking):")
    sorted_instances = sorted(masking_dict["instance_tracking"].items(), key=lambda x: x[1], reverse=True)
    for masked_val, count in sorted_instances[:10]:
        print(f"   • '{masked_val}': {count} входжень")
    if len(sorted_instances) > 10:
        print(f"   ... та ще {len(sorted_instances) - 10} записів")
    print()


def _print_summary(masking_dict: Dict, total_unique: int,
                   output_path: Path, map_path: Path,
                   report_path: Optional[Path], logger,
                   show_statistics: bool = True) -> None:
    """Print masking summary to console (logging.log_statistics: false —
    без блоку статистики)."""
    print()
    print("✅ Маскування завершено успішно!")
    print()
    if show_statistics:
        _print_statistics(masking_dict, total_unique)
    print(f"📁 Файли збережено:")
    print(f"   • Замасковані дані: {output_path.absolute()}")
    print(f"   • Словник замін: {map_path.absolute()}")
    if report_path:
        print(f"   • Звіт: {report_path.absolute()}")

    if logger:
        logger.info(f"Masking completed: {total_unique} unique items masked")
        logger.info(f"Output: {output_path.absolute()}")
        logger.info(f"Mapping: {map_path.absolute()}")


def _save_results(masked_data, is_json: bool, masking_dict: Dict,
                  output_path: Path, map_path: Path, report_path: Path,
                  total_unique: int, args, config, logger,
                  chain=None, password: Optional[str] = None) -> int:
    """Save masked output, mapping (or chain), and report. Returns exit code."""
    re_mask_passes = getattr(args, 're_mask', None)
    system_cfg = getattr(config, 'system', None)

    try:
        # system.backup_enabled: копія наявного вихідного файлу перед перезаписом
        if getattr(system_cfg, 'backup_enabled', False) and output_path.exists():
            suffix = str(getattr(system_cfg, 'backup_suffix', '.bak') or '.bak')
            backup_path = output_path.with_name(output_path.name + suffix)
            shutil.copy2(output_path, backup_path)
            print(f"  Backup of the previous output: {backup_path}")
            if logger:
                logger.info(f"Backup of existing output: {backup_path}")
        out_encoding = masking_dict.get("input_encoding", "utf-8")
        with open(output_path, 'w', encoding=out_encoding, newline='') as f:
            if is_json:
                json.dump(masked_data, f, ensure_ascii=False, indent=2)
            else:
                f.write(masked_data)

        if chain is not None:
            chain_json = map_path.with_name(map_path.name.replace("masking_map_", "masking_chain_", 1))
            chain_dict = chain.to_dict()
            if "input_encoding" in masking_dict:
                chain_dict["input_encoding"] = masking_dict["input_encoding"]
            written_map = _write_mapping(chain_dict, chain_json, password, logger,
                                         kdf=getattr(args, '_kdf', None))
            print(f"  Chain mapping ({len(chain.passes)} passes): {written_map}")
        else:
            written_map = _write_mapping(masking_dict, map_path, password, logger,
                                         kdf=getattr(args, '_kdf', None))
        if password:
            print(f"  Encrypted mapping: {written_map}")
        # security.password_file — лише ЗГЕНЕРОВАНИЙ пароль, після успішного запису mapping
        password_file = getattr(args, '_password_file', None)
        if password and password_file:
            atomic_write_private(Path(password_file), (password + "\n").encode("utf-8"))
            if logger:
                logger.info(f"Generated password saved to {password_file}")

        # Generate report
        if not args.no_report:
            _write_report(report_path, masking_dict, Path(args.input),
                          output_path, is_json, total_unique,
                          re_mask_passes, args, config)

        _print_summary(
            masking_dict, total_unique, output_path, written_map,
            report_path if not args.no_report else None, logger,
            show_statistics=getattr(getattr(config, 'logging', None), 'log_statistics', True) is not False,
        )
        return EXIT_OK

    except (OSError, PermissionError, json.JSONDecodeError, UnicodeEncodeError, RuntimeError) as e:
        print(f"❌ Помилка збереження файлів: {e}")
        if logger:
            logger.error(f"Error saving files: {e}")
        return EXIT_ERROR


def main(argv=None) -> int:
    """CLI entry point. Повертає код виходу (0/1/2); обгортки роблять
    sys.exit(main()), тому помилки більше не завершуються exit 0."""
    # Fix Unicode output on Windows (cp1252 console): інакше «✅» у підсумку
    # падав UnicodeEncodeError уже ПІСЛЯ запису файлів (unmask мав цей фікс, mask — ні)
    if sys.platform == 'win32' and getattr(sys.stdout, 'encoding', 'utf-8').lower().replace('-', '') != 'utf8':
        import io
        sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
        sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8', errors='replace')

    parser = _build_parser()
    args = parser.parse_args(argv)

    # ================================================================
    # Handle --init-config (early exit)
    # ================================================================
    if args.init_config:
        if Path("config.yaml").exists() and not args.force:
            print("Error: config.yaml already exists (use --force to overwrite)")
            return EXIT_ERROR
        generate_default_config("config.yaml")
        print("Generated config.yaml")
        return EXIT_OK

    # ================================================================
    # Handle --list-types (early exit)
    # ================================================================
    if SELECTIVE_AVAILABLE and getattr(args, 'list_types', False):
        print(get_types_help())
        return EXIT_OK

    # ================================================================
    # Setup: config, logging, filters, system settings
    # ================================================================
    config, config_error = _load_config(args)
    if config_error:
        print(f"Error: {config_error}")
        return EXIT_ERROR
    args._strict = bool(CONFIG_AVAILABLE and config is not None and is_strict(config))
    logger = _setup_logger(args, config)

    if args.debug:
        _cfg.DEBUG_MODE = True

    cfg_sel_error = _selective_from_config(args, config)
    if cfg_sel_error:
        print(f"Error: {cfg_sel_error}")
        return EXIT_ERROR
    filter_error = _apply_selective_filters(args, logger)
    if filter_error:
        print(f"Error: {filter_error}")
        return EXIT_USAGE
    settings_error = _apply_config_settings(args, config, logger)
    if settings_error:
        print(f"Error: {settings_error}")
        return EXIT_ERROR
    for strict_error in getattr(args, '_strict_errors', []):
        print(f"Error: strict_mode: {strict_error}")
    if getattr(args, '_strict_errors', []):
        return EXIT_ERROR

    if getattr(args, 'list_exclusions', False):
        from datamasking.masking import exclusions as _exclusions
        excl = getattr(args, '_exclusions', None) or _exclusions.build(None)
        print(_exclusions.describe(excl), end="")
        return EXIT_OK

    if logger:
        logger.info(f"Masking flags: SURNAMES={_cfg.MASK_SURNAMES}, NAMES={_cfg.MASK_NAMES}, "
                    f"PATRONYMICS={_cfg.MASK_PATRONYMICS}, IPN={_cfg.MASK_IPN}, "
                     f"PASSPORT={_cfg.MASK_PASSPORT}, MILITARY_ID={_cfg.MASK_MILITARY_ID}, "
                     f"RANKS={_cfg.MASK_RANKS}, BRIGADES={_cfg.MASK_BRIGADES}, "
                     f"UNITS={_cfg.MASK_UNITS}, ORDERS={_cfg.MASK_ORDERS}, "
                     f"DOCUMENT_NUMBERS={_cfg.MASK_DOCUMENT_NUMBERS}, "
                     f"BR_NUMBERS={_cfg.MASK_BR_NUMBERS}, DATES={_cfg.MASK_DATES}")

    # ================================================================
    # Input file validation and path setup
    # ================================================================
    input_path = Path(args.input)
    if not input_path.exists():
        print(f"Error: {args.input} not found")
        if logger:
            logger.error(f"Input file not found: {args.input}")
        return EXIT_ERROR

    output_path, map_path, report_path, timestamp, random_suffix = \
        _prepare_output_paths(args, input_path)

    path_error = _validate_output_paths(args, input_path, output_path)
    if path_error:
        print(f"Error: {path_error}")
        if logger:
            logger.error(path_error)
        return EXIT_USAGE

    # Пароль визначаємо ДО будь-якого запису: помилка тут не лишає
    # напівготових файлів на диску
    password = None
    if getattr(args, 'encrypt', False) and not is_encryption_available():
        # Ядро без extras: чиста помилка ДО запису файлів, а не traceback
        print("Error: --encrypt requires the 'cryptography' package "
              "(pip install 'data-masking[security]')")
        return EXIT_ERROR
    if SECURITY_AVAILABLE and getattr(args, 'encrypt', False):
        password, pw_error = _resolve_password(args, config, logger)
        if pw_error:
            print(f"Error: {pw_error}")
            if logger:
                logger.error(pw_error)
            return EXIT_USAGE
    elif getattr(args, 'encrypt', False):
        print("Error: --encrypt requires the 'cryptography' package (pip install 'data-masking[security]')")
        return EXIT_ERROR

    is_json = input_path.suffix.lower() == '.json'

    masking_dict = {
        "version": _cfg.__version__,
        "timestamp": datetime.now().isoformat(),
        "input_file": str(input_path),
        "statistics": {},
        "mappings": {k: {} for k in [
            "ipn", "passport_id", "military_id", "surname", "name",
            "military_unit", "order_number", "order_number_with_letters",
            "br_number", "br_number_slash", "br_number_complex",
            "rank", "brigade_number", "date", "date_text", "patronymic",
            "initials"
        ]},
        "instance_tracking": {}
    }
    instance_counters: Dict[str, int] = {}

    # ================================================================
    # Read input
    # ================================================================
    print(f"Data Masking Script v{_cfg.__version__}")
    print(f"Processing {input_path}...")
    print(f"Output format: {'JSON' if is_json else 'TXT'}")
    if logger:
        logger.info(f"Processing {input_path}")

    import time as _time
    t_start = _time.perf_counter()
    input_data = _read_input(input_path, is_json, logger, masking_dict)
    if input_data is None:
        return EXIT_ERROR
    t_read = _time.perf_counter()
    from datamasking.masking import custom as _custom
    _custom.WARN_COUNTS.clear()

    # ================================================================
    # Run masking pipeline
    # ================================================================
    masked_data, total_unique, chain = _run_masking(
        input_data, is_json, masking_dict, instance_counters,
        args, logger, timestamp, random_suffix
    )
    t_mask = _time.perf_counter()
    for name, count in _custom.WARN_COUNTS.items():
        print(f"Warning: custom pattern {name!r}: {count} match(es) left unmasked (action: warn)",
              file=sys.stderr)
        if logger:
            logger.warning(f"Custom pattern {name}: {count} match(es) left unmasked")

    # ================================================================
    # Save results
    # ================================================================
    rc = _save_results(
        masked_data, is_json, masking_dict,
        output_path, map_path, report_path,
        total_unique, args, config, logger,
        chain=chain, password=password,
    )
    # logging.log_performance — час етапів
    if _cfg.LOG_PERFORMANCE and logger:
        t_save = _time.perf_counter()
        logger.info(f"Performance: read {t_read - t_start:.3f}s, mask {t_mask - t_read:.3f}s, "
                    f"save {t_save - t_mask:.3f}s, total {t_save - t_start:.3f}s")
    return rc
