#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
CLI entry point and orchestration for data masking.

Extracted from data_masking.py during v2.5.0 refactoring.
"""

import json
import os
import random
import argparse
from pathlib import Path
from datetime import datetime
from typing import Any, Dict, Optional, Tuple

from masking import constants as _cfg
from masking.helpers import validate_file_size
from masking.engine import (
    mask_text_context_aware, mask_json_recursive,
)

# ============================================================================
# OPTIONAL MODULES
# ============================================================================
import logging as _logging
_opt_logger = _logging.getLogger(__name__)

try:
    from modules.selective import SelectiveFilter, apply_filter_to_globals, get_available_types
    SELECTIVE_AVAILABLE = True
except ImportError:
    SELECTIVE_AVAILABLE = False
    _opt_logger.debug("modules.selective not available — --only/--exclude disabled")

try:
    from modules.re_mask import ReMasker, MappingChain, make_empty_masking_dict
    REMASK_AVAILABLE = True
except ImportError:
    REMASK_AVAILABLE = False
    _opt_logger.debug("modules.re_mask not available — re-masking disabled")

try:
    from modules.security import MappingSecurityManager
    SECURITY_AVAILABLE = True
except ImportError:
    SECURITY_AVAILABLE = False
    _opt_logger.debug("modules.security not available — encryption disabled")

try:
    from modules.config import ConfigLoader
    CONFIG_AVAILABLE = True
except ImportError:
    CONFIG_AVAILABLE = False
    _opt_logger.debug("modules.config not available — YAML config disabled")

try:
    from modules.masking_logger import setup_logging
    LOGGING_AVAILABLE = True
except ImportError:
    LOGGING_AVAILABLE = False
    _opt_logger.debug("modules.masking_logger not available — structured logging disabled")

try:
    from modules.password_generator import generate_password
    PASSWORD_GENERATOR_AVAILABLE = True
except ImportError:
    PASSWORD_GENERATOR_AVAILABLE = False
    _opt_logger.debug("modules.password_generator not available — password generation disabled")


# ============================================================================
# UTILITY FUNCTIONS
# ============================================================================

def generate_default_config(output_path: str) -> None:
    """Generate a default config.yaml file."""
    config_content = f"""\
# Data Masking Configuration v{_cfg.__version__}
# Generated by data_masking.py

system:
  version: "v{_cfg.__version__}"
  hash_algorithm: "blake2b"
  preserve_case: true
  debug_mode: false

security:
  encrypt_output: false
  password_generation: true
  password_env_var: "DATA_MASKING_PASSWORD"
  password_length: 24

masking_rules:
  enable_ranks: true
  enable_names: true
  enable_ipn: true
  enable_passport: true
  enable_military_id: true
  enable_dates: true
  enable_brigades: true
  enable_units: true
  enable_orders: true
  enable_br_numbers: true

logging:
  level: "INFO"
  file: null
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

router_rules:
  default_action: "mask"
"""
    Path(output_path).write_text(config_content, encoding='utf-8')


def generate_password_from_config(config) -> str:
    """Generate a secure password, optionally using config settings."""
    import secrets
    import string
    length = 24
    if config is not None:
        length = getattr(getattr(config, 'security', None),
                         'password_length', 24)
    alphabet = string.ascii_letters + string.digits + "!@#$%^&*"
    return ''.join(secrets.choice(alphabet) for _ in range(length))


def _build_parser() -> argparse.ArgumentParser:
    """Build and return the CLI argument parser."""
    parser = argparse.ArgumentParser(
        description=f"Data Masking Script v{_cfg.__version__}",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("-V", "--version", action="version",
                        version=f"%(prog)s {_cfg.__version__}")
    parser.add_argument("-i", "--input", default="input.txt", help="Input file")
    parser.add_argument("-o", "--output", help="Output file")
    parser.add_argument("--no-report", action="store_true", help="No report")
    parser.add_argument("--debug", action="store_true", help="Debug mode")
    parser.add_argument("--init-config", action="store_true",
                        help="Generate default config.yaml and exit")
    parser.add_argument("--config", type=str, default=None,
                        help="Path to YAML configuration file")
    parser.add_argument("--log-level", type=str, default=None,
                        choices=["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"],
                        help="Logging level")
    parser.add_argument("--log-file", type=str, default=None,
                        help="Path to log file")

    if SELECTIVE_AVAILABLE:
        parser.add_argument("--only", nargs="+", metavar="TYPE",
                            help="Mask only these types")
        parser.add_argument("--exclude", nargs="+", metavar="TYPE",
                            help="Mask everything except these types")
        parser.add_argument("--list-types", action="store_true",
                            help="List available masking types and exit")

    if SECURITY_AVAILABLE:
        parser.add_argument("--encrypt", action="store_true",
                            help="Encrypt the mapping file")
        parser.add_argument("--password", type=str, default=None,
                            help="Password for encryption")
        parser.add_argument("--password-env", type=str, default=None,
                            help="Environment variable name containing the password")

    if REMASK_AVAILABLE:
        parser.add_argument("--re-mask", type=int, default=None, metavar="N",
                            help="Number of re-masking passes (2-10)")

    return parser


def _load_config(args) -> Optional[Any]:
    """Load configuration from YAML file if available."""
    if not CONFIG_AVAILABLE:
        return None

    config_path = args.config
    if config_path is None and Path("config.yaml").exists():
        config_path = "config.yaml"
    if not config_path:
        return None

    try:
        loader = ConfigLoader(config_path)
        config = loader.load()
        print(f"Loaded config from {config_path}")
        return config
    except (FileNotFoundError, PermissionError, ValueError, OSError) as e:
        print(f"Warning: could not load config from {config_path}: {e}")
        return None


def _setup_logger(args, config) -> Optional[Any]:
    """Set up structured logging."""
    if not LOGGING_AVAILABLE:
        return None

    log_level = args.log_level
    log_file = args.log_file

    if config is not None:
        if log_level is None:
            log_level = getattr(getattr(config, 'logging', None), 'level', None)
        if log_file is None:
            log_file = getattr(getattr(config, 'logging', None), 'file', None)

    if log_level is None:
        log_level = "INFO"

    try:
        logger = setup_logging(level=log_level, log_file=log_file)
        logger.info(f"Data Masking Script v{_cfg.__version__} started")
        return logger
    except (ValueError, OSError, TypeError) as e:
        print(f"Warning: could not setup logging: {e}")
        return None


def _apply_selective_filters(args, logger) -> None:
    """Apply --only / --exclude selective masking filters."""
    if not SELECTIVE_AVAILABLE:
        return

    only_types = getattr(args, 'only', None)
    exclude_types = getattr(args, 'exclude', None)

    if not only_types and not exclude_types:
        return

    type_flag_map = {
        "names": "MASK_NAMES",
        "ipn": "MASK_IPN",
        "passport": "MASK_PASSPORT",
        "military_id": "MASK_MILITARY_ID",
        "ranks": "MASK_RANKS",
        "brigades": "MASK_BRIGADES",
        "units": "MASK_UNITS",
        "orders": "MASK_ORDERS",
        "br_numbers": "MASK_BR_NUMBERS",
        "dates": "MASK_DATES",
    }

    if only_types:
        _cfg.MASK_NAMES = False
        _cfg.MASK_IPN = False
        _cfg.MASK_PASSPORT = False
        _cfg.MASK_MILITARY_ID = False
        _cfg.MASK_RANKS = False
        _cfg.MASK_BRIGADES = False
        _cfg.MASK_UNITS = False
        _cfg.MASK_ORDERS = False
        _cfg.MASK_BR_NUMBERS = False
        _cfg.MASK_DATES = False
        for t in only_types:
            t_lower = t.lower()
            if t_lower in type_flag_map:
                setattr(_cfg, type_flag_map[t_lower], True)
            else:
                print(f"Warning: unknown type '{t}', ignoring")
                if logger:
                    logger.warning(f"Unknown selective type: {t}")
        print(f"Selective masking: --only {' '.join(only_types)}")
        if logger:
            logger.info(f"Selective masking: --only {' '.join(only_types)}")

    elif exclude_types:
        for t in exclude_types:
            t_lower = t.lower()
            if t_lower in type_flag_map:
                setattr(_cfg, type_flag_map[t_lower], False)
            else:
                print(f"Warning: unknown type '{t}', ignoring")
                if logger:
                    logger.warning(f"Unknown selective type: {t}")
        print(f"Selective masking: --exclude {' '.join(exclude_types)}")
        if logger:
            logger.info(f"Selective masking: --exclude {' '.join(exclude_types)}")


def _apply_config_settings(args, config, logger) -> None:
    """Apply config-based masking rules and system settings."""
    if config is None:
        return

    # Masking rules from config (only if --only/--exclude not specified)
    masking_rules = getattr(config, 'masking_rules', None)
    if masking_rules is not None:
        only_types = getattr(args, 'only', None) if SELECTIVE_AVAILABLE else None
        exclude_types = getattr(args, 'exclude', None) if SELECTIVE_AVAILABLE else None

        if not only_types and not exclude_types:
            config_rules_map = {
                'enable_ranks': 'MASK_RANKS',
                'enable_names': 'MASK_NAMES',
                'enable_ipn': 'MASK_IPN',
                'enable_passport': 'MASK_PASSPORT',
                'enable_military_id': 'MASK_MILITARY_ID',
                'enable_dates': 'MASK_DATES',
                'enable_brigades': 'MASK_BRIGADES',
                'enable_units': 'MASK_UNITS',
                'enable_orders': 'MASK_ORDERS',
                'enable_br_numbers': 'MASK_BR_NUMBERS',
            }
            for config_key, global_var in config_rules_map.items():
                value = getattr(masking_rules, config_key, None)
                if value is not None:
                    setattr(_cfg, global_var, bool(value))
                    if logger:
                        logger.debug(f"Config: {config_key} = {value}")

    # System settings from config
    system_cfg = getattr(config, 'system', None)
    if system_cfg is not None:
        cfg_debug = getattr(system_cfg, 'debug_mode', None)
        if cfg_debug is not None and not args.debug:
            _cfg.DEBUG_MODE = bool(cfg_debug)

        cfg_preserve_case = getattr(system_cfg, 'preserve_case', None)
        if cfg_preserve_case is not None:
            _cfg.PRESERVE_CASE = bool(cfg_preserve_case)

        cfg_hash = getattr(system_cfg, 'hash_algorithm', None)
        if cfg_hash is not None:
            _cfg.HASH_ALGORITHM = str(cfg_hash)


def _prepare_output_paths(args, input_path: Path) -> Tuple[Path, Path, Path, str, int]:
    """Determine output, mapping, and report file paths."""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    random_suffix = random.randint(100, 999)
    is_json = input_path.suffix.lower() == '.json'

    if args.output:
        output_path = Path(args.output)
    else:
        output_path = Path(f"output_{timestamp}_{random_suffix}{'.json' if is_json else '.txt'}")

    map_path = Path(f"masking_map_{timestamp}_{random_suffix}.json")
    report_path = Path(f"masking_report_{timestamp}_{random_suffix}.txt")

    return output_path, map_path, report_path, timestamp, random_suffix


def _read_input(input_path: Path, is_json: bool, logger):
    """Read input file (JSON or text)."""
    try:
        validate_file_size(input_path)
        with open(input_path, 'r', encoding='utf-8', newline='') as f:
            if is_json:
                return json.load(f)
            else:
                return f.read()
    except (FileNotFoundError, PermissionError, OSError, json.JSONDecodeError,
            UnicodeDecodeError, ValueError) as e:
        print(f"Error reading file: {e}")
        if logger:
            logger.error(f"Error reading file: {e}")
        return None


def _run_masking(input_data, is_json: bool, masking_dict: Dict,
                 instance_counters: Dict, args, logger,
                 timestamp: str, random_suffix: int) -> Tuple[Any, int]:
    """Execute single-pass or multi-pass masking."""
    re_mask_passes = getattr(args, 're_mask', None)

    if re_mask_passes is not None:
        if re_mask_passes < 2:
            print("Warning: --re-mask requires at least 2 passes, using single-pass mode")
            if logger:
                logger.warning("--re-mask value < 2, falling back to single-pass")
            re_mask_passes = None
        elif re_mask_passes > 10:
            print(f"Warning: --re-mask capped at 10 passes (was {re_mask_passes})")
            if logger:
                logger.warning(f"--re-mask capped at 10 (requested {re_mask_passes})")
            re_mask_passes = 10

    if REMASK_AVAILABLE and re_mask_passes and re_mask_passes > 1:
        return _run_multi_pass_masking(
            input_data, is_json, masking_dict, args, logger,
            re_mask_passes, timestamp, random_suffix
        )
    else:
        return _run_single_pass_masking(
            input_data, is_json, masking_dict, instance_counters, logger
        )


def _run_multi_pass_masking(input_data, is_json: bool, masking_dict: Dict,
                            args, logger, re_mask_passes: int,
                            timestamp: str, random_suffix: int) -> Tuple[Any, int]:
    """Execute multi-pass re-masking with chain tracking."""
    if logger:
        logger.info(f"Starting multi-pass re-masking ({re_mask_passes} passes)")

    chain = MappingChain()
    masked_data = input_data

    for pass_num in range(1, re_mask_passes + 1):
        print(f"  Прохід {pass_num}/{re_mask_passes}...")
        if logger:
            logger.info(f"Re-masking pass {pass_num}/{re_mask_passes}")

        pass_dict = make_empty_masking_dict(_cfg.__version__)
        pass_counters = {}

        if is_json:
            masked_data = mask_json_recursive(masked_data, pass_dict, pass_counters)
        else:
            masked_data = mask_text_context_aware(masked_data, pass_dict, pass_counters)

        pass_dict["instance_tracking"] = pass_counters
        for category, mappings in pass_dict["mappings"].items():
            pass_dict["statistics"][category] = len(mappings)
        chain.add_pass(pass_dict)

    chain_path = Path(f"masking_chain_{timestamp}_{random_suffix}.json")
    chain.save(chain_path)
    print(f"  Chain mapping ({re_mask_passes} passes): {chain_path}")
    if logger:
        logger.info(f"Chain mapping saved to {chain_path}")

    masking_dict["instance_tracking"] = {}
    total_unique = 0
    for p in chain.passes:
        for cat, count in p.get("statistics", {}).items():
            masking_dict["statistics"][cat] = masking_dict["statistics"].get(cat, 0) + count
            if cat != "total_masked":
                total_unique += count
    masking_dict["statistics"]["total_masked"] = total_unique

    return masked_data, total_unique


def _run_single_pass_masking(input_data, is_json: bool, masking_dict: Dict,
                             instance_counters: Dict, logger) -> Tuple[Any, int]:
    """Execute single-pass masking."""
    if logger:
        logger.info("Starting single-pass masking")

    if is_json:
        masked_data = mask_json_recursive(input_data, masking_dict, instance_counters)
    else:
        masked_data = mask_text_context_aware(input_data, masking_dict, instance_counters)

    masking_dict["instance_tracking"] = instance_counters

    total_unique = 0
    for category, mappings in masking_dict["mappings"].items():
        count = len(mappings)
        masking_dict["statistics"][category] = count
        total_unique += count
    masking_dict["statistics"]["total_masked"] = total_unique

    return masked_data, total_unique


def _handle_encryption(args, config, masking_dict: Dict, map_path: Path,
                       logger) -> None:
    """Encrypt the mapping file if --encrypt is requested."""
    if not SECURITY_AVAILABLE or not getattr(args, 'encrypt', False):
        return

    enc_path = map_path.with_suffix('.enc')
    password = getattr(args, 'password', None)

    if not password:
        password_env = getattr(args, 'password_env', None)
        if password_env:
            password = os.environ.get(password_env)
            if not password:
                print(f"Warning: environment variable '{password_env}' is not set or empty")
                if logger:
                    logger.warning(f"Environment variable '{password_env}' is not set or empty")
                password = generate_password_from_config(config)
                print(f"  Generated password: {password}")
        else:
            password = generate_password_from_config(config)
            print(f"  Generated password: {password}")

    manager = MappingSecurityManager()
    manager.encrypt_mapping(masking_dict, password, enc_path)
    print(f"  Encrypted mapping: {enc_path}")
    if logger:
        logger.info(f"Mapping encrypted to {enc_path}")


def _write_report(report_path: Path, masking_dict: Dict, input_path: Path,
                  output_path: Path, is_json: bool, total_unique: int,
                  re_mask_passes, args, config) -> None:
    """Generate the detailed masking report file."""
    with open(report_path, 'w', encoding='utf-8') as f:
        f.write("=" * 60 + "\n")
        f.write("ЗВІТ МАСКУВАННЯ ДАНИХ\n")
        f.write("=" * 60 + "\n\n")
        f.write(f"Версія: {_cfg.__version__}\n")
        f.write(f"Дата та час: {masking_dict['timestamp']}\n")
        f.write(f"Вхідний файл: {input_path}\n")
        f.write(f"Вихідний файл: {output_path}\n")
        f.write(f"Формат: {'JSON' if is_json else 'TXT'}\n")

        f.write("\n" + "-" * 60 + "\n")
        f.write("КОНФІГУРАЦІЯ МАСКУВАННЯ\n")
        f.write("-" * 60 + "\n\n")
        f.write(f"  Імена (MASK_NAMES): {_cfg.MASK_NAMES}\n")
        f.write(f"  ІПН (MASK_IPN): {_cfg.MASK_IPN}\n")
        f.write(f"  Паспорти (MASK_PASSPORT): {_cfg.MASK_PASSPORT}\n")
        f.write(f"  Військові ID (MASK_MILITARY_ID): {_cfg.MASK_MILITARY_ID}\n")
        f.write(f"  Звання (MASK_RANKS): {_cfg.MASK_RANKS}\n")
        f.write(f"  Бригади (MASK_BRIGADES): {_cfg.MASK_BRIGADES}\n")
        f.write(f"  Частини (MASK_UNITS): {_cfg.MASK_UNITS}\n")
        f.write(f"  Накази (MASK_ORDERS): {_cfg.MASK_ORDERS}\n")
        f.write(f"  БР номери (MASK_BR_NUMBERS): {_cfg.MASK_BR_NUMBERS}\n")
        f.write(f"  Дати (MASK_DATES): {_cfg.MASK_DATES}\n")
        f.write(f"  Збереження регістру (PRESERVE_CASE): {_cfg.PRESERVE_CASE}\n")
        f.write(f"  Алгоритм хешування: {_cfg.HASH_ALGORITHM}\n")

        if re_mask_passes and re_mask_passes > 1:
            f.write(f"\n  Режим: повторне маскування ({re_mask_passes} проходів)\n")
        else:
            f.write(f"\n  Режим: одинарне маскування\n")

        if config is not None:
            f.write(f"  Конфігурація: {args.config or 'config.yaml'}\n")

        f.write("\n" + "-" * 60 + "\n")
        f.write("СТАТИСТИКА МАСКУВАННЯ\n")
        f.write("-" * 60 + "\n\n")
        f.write(f"Загальна кількість УНІКАЛЬНИХ замаскованих елементів: {total_unique}\n\n")

        for key, value in sorted(masking_dict["statistics"].items()):
            if key != "total_masked" and value > 0:
                f.write(f"  • {key}: {value} (унікальних оригіналів)\n")

        f.write("\n" + "=" * 60 + "\n")
        f.write("СТАТИСТИКА ВХОДЖЕНЬ (Instance Tracking)\n")
        f.write("-" * 60 + "\n\n")

        sorted_report_instances = sorted(
            masking_dict["instance_tracking"].items(),
            key=lambda x: x[1],
            reverse=True
        )
        for masked_val, count in sorted_report_instances:
            f.write(f"  • '{masked_val}': {count} входжень\n")

        f.write("\n" + "=" * 60 + "\n")
        f.write(f"Кінець звіту. Всього записів у instance tracking: "
                f"{len(masking_dict['instance_tracking'])}\n")
        f.write("=" * 60 + "\n")


def _print_summary(masking_dict: Dict, total_unique: int,
                   output_path: Path, map_path: Path,
                   report_path: Optional[Path], logger) -> None:
    """Print masking summary to console."""
    print()
    print("✅ Маскування завершено успішно!")
    print()
    print(f"📊 Статистика:")
    print(f"   Загальна кількість УНІКАЛЬНИХ замаскованих елементів: {total_unique}")
    for key, value in sorted(masking_dict["statistics"].items()):
        if key != "total_masked" and value > 0:
            print(f"   • {key}: {value} (унікальних оригіналів)")
    print()
    print(f"   Статистика входжень (Instance Tracking):")
    sorted_instances = sorted(masking_dict["instance_tracking"].items(), key=lambda x: x[1], reverse=True)
    for masked_val, count in sorted_instances[:10]:
        print(f"   • '{masked_val}': {count} входжень")
    if len(sorted_instances) > 10:
        print(f"   ... та ще {len(sorted_instances) - 10} записів")

    print()
    print(f"📁 Файли збережено:")
    print(f"   • Замасковані дані: {output_path.absolute()}")
    print(f"   • Словник замін: {map_path.absolute()}")
    if report_path:
        print(f"   • Звіт: {report_path.absolute()}")

    if logger:
        logger.info(f"Masking completed: {total_unique} unique items masked")
        logger.info(f"Output: {output_path.absolute()}")
        logger.info(f"Mapping: {map_path.absolute()}")


def _save_results(masked_data, is_json: bool, masking_dict: Dict,
                  output_path: Path, map_path: Path, report_path: Path,
                  total_unique: int, args, config, logger) -> None:
    """Save masked output, mapping, optional encryption, and report."""
    re_mask_passes = getattr(args, 're_mask', None)

    try:
        with open(output_path, 'w', encoding='utf-8', newline='') as f:
            if is_json:
                json.dump(masked_data, f, ensure_ascii=False, indent=2)
            else:
                f.write(masked_data)

        # Save mapping (single-pass only; chain saves its own file)
        if not (REMASK_AVAILABLE and re_mask_passes and re_mask_passes > 1):
            with open(map_path, 'w', encoding='utf-8') as f:
                json.dump(masking_dict, f, ensure_ascii=False, indent=2)

            _handle_encryption(args, config, masking_dict, map_path, logger)

        # Generate report
        if not args.no_report:
            _write_report(report_path, masking_dict, Path(args.input),
                          output_path, is_json, total_unique,
                          re_mask_passes, args, config)

        _print_summary(
            masking_dict, total_unique, output_path, map_path,
            report_path if not args.no_report else None, logger
        )

    except (OSError, PermissionError, json.JSONDecodeError, UnicodeEncodeError) as e:
        print(f"❌ Помилка збереження файлів: {e}")
        if logger:
            logger.error(f"Error saving files: {e}")


def main():
    parser = _build_parser()
    args = parser.parse_args()

    # ================================================================
    # Handle --init-config (early exit)
    # ================================================================
    if args.init_config:
        generate_default_config("config.yaml")
        print("Generated config.yaml")
        return

    # ================================================================
    # Handle --list-types (early exit)
    # ================================================================
    if SELECTIVE_AVAILABLE and getattr(args, 'list_types', False):
        types = sorted(get_available_types())
        print("Available masking types:")
        for t in types:
            print(f"  - {t}")
        return

    # ================================================================
    # Setup: config, logging, filters, system settings
    # ================================================================
    config = _load_config(args)
    logger = _setup_logger(args, config)

    if args.debug:
        _cfg.DEBUG_MODE = True

    _apply_selective_filters(args, logger)
    _apply_config_settings(args, config, logger)

    if logger:
        logger.info(f"Masking flags: NAMES={_cfg.MASK_NAMES}, IPN={_cfg.MASK_IPN}, "
                     f"PASSPORT={_cfg.MASK_PASSPORT}, MILITARY_ID={_cfg.MASK_MILITARY_ID}, "
                     f"RANKS={_cfg.MASK_RANKS}, BRIGADES={_cfg.MASK_BRIGADES}, "
                     f"UNITS={_cfg.MASK_UNITS}, ORDERS={_cfg.MASK_ORDERS}, "
                     f"BR_NUMBERS={_cfg.MASK_BR_NUMBERS}, DATES={_cfg.MASK_DATES}")

    # ================================================================
    # Input file validation and path setup
    # ================================================================
    input_path = Path(args.input)
    if not input_path.exists():
        print(f"Error: {args.input} not found")
        if logger:
            logger.error(f"Input file not found: {args.input}")
        return

    output_path, map_path, report_path, timestamp, random_suffix = \
        _prepare_output_paths(args, input_path)

    is_json = input_path.suffix.lower() == '.json'

    masking_dict = {
        "version": _cfg.__version__,
        "timestamp": datetime.now().isoformat(),
        "input_file": str(input_path),
        "statistics": {},
        "mappings": {k: {} for k in [
            "ipn", "passport_id", "military_id", "surname", "name",
            "military_unit", "order_number", "order_number_with_letters",
            "br_number", "br_number_slash", "br_number_complex",
            "rank", "brigade_number", "date", "date_text", "patronymic"
        ]},
        "instance_tracking": {}
    }
    instance_counters = {}

    # ================================================================
    # Read input
    # ================================================================
    print(f"Data Masking Script v{_cfg.__version__}")
    print(f"Processing {input_path}...")
    print(f"Output format: {'JSON' if is_json else 'TXT'}")
    if logger:
        logger.info(f"Processing {input_path}")

    input_data = _read_input(input_path, is_json, logger)
    if input_data is None:
        return

    # ================================================================
    # Run masking pipeline
    # ================================================================
    masked_data, total_unique = _run_masking(
        input_data, is_json, masking_dict, instance_counters,
        args, logger, timestamp, random_suffix
    )

    # ================================================================
    # Save results
    # ================================================================
    _save_results(
        masked_data, is_json, masking_dict,
        output_path, map_path, report_path,
        total_unique, args, config, logger
    )
